const companyService = require('../../services/company/companyService');
const { resolveCompanyId } = require('../../utils/companyScope');
const scheduleMaterializer = require('../../jobs/materializeSchedules');

function companyId(req) {
  return resolveCompanyId(req);
}

const READINESS_LABELS = Object.freeze({
  company_not_active_and_verified: 'activate and verify the partner company',
  bus_service_listing_missing: 'create the bus service listing',
  route_not_active: 'activate the selected route',
  route_segments_incomplete: 'complete the route stops and segments',
  vehicle_not_active: 'activate the selected vehicle',
  operator_permit_missing_or_expired: 'add a valid vehicle operating permit',
  inspection_missing_or_expired: 'add a valid vehicle inspection',
  insurance_missing_or_expired: 'add valid vehicle insurance',
  published_seat_map_missing: 'publish the vehicle seat map',
  active_fare_product_missing: 'activate a fare plan for this route',
  fare_snapshot_missing: 'add a positive route fare',
  currency_missing: 'set the company operating currency',
  departure_time_missing: 'set a valid departure time',
  departure_must_be_future: 'choose a future departure date',
  arrival_must_be_after_departure: 'set arrival after departure',
  seat_segment_inventory_missing: 'generate seat inventory',
  vehicle_time_conflict: 'resolve the vehicle time conflict',
});

function readinessText(failures = []) {
  return [...new Set((failures || []).filter(Boolean).map((failure) => READINESS_LABELS[failure] || String(failure).replace(/_/g, ' ')))].join(', ');
}

function materializationSummary(result = {}) {
  const expected = Number(result.expected || 0);
  const created = Number(result.created || 0);
  const existing = Number(result.existing || 0);
  const published = Number(result.published || 0);
  const draft = Number(result.draft || 0);
  const skipped = Number(result.skipped || 0);
  const pending = Number(result.pending || 0);
  const ready = created + existing;
  const blockers = readinessText(result.failures || []);
  let message;
  if (pending > 0) {
    message = `${ready} dated departure${ready === 1 ? '' : 's'} ${ready === 1 ? 'is' : 'are'} available now (${created} created, ${existing} already existed). ${pending} remaining date${pending === 1 ? ' is' : 's are'} queued for the background rolling worker and will continue after this page redirects.`;
  } else {
    message = `${ready} dated departure${ready === 1 ? '' : 's'} ${ready === 1 ? 'is' : 'are'} covered in the current rolling window: ${created} created now and ${existing} already existed.`;
  }
  if (published || draft) message += ` Publication: ${published} Published and ${draft} Draft.`;
  if (draft && blockers) message += ` Draft blockers: ${blockers}.`;
  return { expected, created, existing, published, draft, skipped, pending, ready, blockers, message };
}

async function materializeActiveRule(req, rule) {
  if (!rule || String(rule.status || '').toLowerCase() !== 'active') return null;
  let result;
  try {
    result = await scheduleMaterializer.materializeRuleById(companyId(req), rule.id, new Date(), { waitForLeaseMs: 1500, maxCreates: 1 });
  } catch (error) {
    const wrapped = new Error(`The recurring rule was saved, but dated departures could not be generated immediately: ${error.message || 'temporary database error'}. The queued worker retry remains available after the database is healthy.`);
    wrapped.status = Number(error.status || 0) >= 500 ? 503 : Number(error.status || 422);
    throw wrapped;
  }
  const summary = materializationSummary(result);
  if (result.busy) {
    scheduleMaterializer.queueRuleMaterialization(companyId(req), rule.id, { delayMs: 1500, resetPublicationBlocker: true });
    return {
      ...result,
      ...summary,
      pending: Math.max(1, Number(summary.pending || 0)),
      message: 'The recurring rule was saved. Its rolling window is already being generated by the lease-protected background rolling worker; reload Departures & Fares shortly to see the completed dates.',
    };
  }
  if (summary.pending > 0) scheduleMaterializer.queueRuleMaterialization(companyId(req), rule.id, { delayMs: 1500, resetPublicationBlocker: true });
  if (!summary.ready) {
    const details = (result.failures || []).filter(Boolean).join('; ');
    const error = new Error(`The recurring rule was saved, but no dated departures exist in its current 30-day window. ${details || 'Check the start date, end date, operating weekdays, route, vehicle seat map, fare plan, and departure readiness, then retry.'}`);
    error.status = 422;
    throw error;
  }
  return { ...result, ...summary };
}

function flashMaterialization(req, label, materialized) {
  if (!req.flash || !materialized) return;
  const type = materialized.skipped || materialized.draft || materialized.pending ? 'warning' : 'success';
  req.flash(type, `${label} ${materialized.message} The rolling window stays current, and one new far-end day is added automatically each day.`);
}

function handleRuleError(req, res, next, error) {
  if ([422, 503].includes(Number(error?.status)) && req.flash) {
    req.flash(Number(error.status) === 503 ? 'warning' : 'error', error.message);
    return res.redirect('/company/schedules-fares');
  }
  return next(error);
}

function rollingSchedulePayload(payload = {}) {
  const departAt = String(payload.departAt || '').trim();
  const timeMatch = departAt.match(/(?:T|\s)((?:[01]\d|2[0-3]):[0-5]\d)/);
  const startDate = departAt.slice(0, 10);
  if (!/^\d{4}-\d{2}-\d{2}$/.test(startDate) || !timeMatch) {
    const error = new Error('First departure date and time are required');
    error.status = 400;
    throw error;
  }

  let durationMinutes;
  if (payload.arriveAt) {
    const departTime = new Date(departAt).getTime();
    const arrivalTime = new Date(payload.arriveAt).getTime();
    if (Number.isFinite(departTime) && Number.isFinite(arrivalTime) && arrivalTime > departTime) {
      durationMinutes = Math.round((arrivalTime - departTime) / 60000);
    }
  }

  return {
    routeId: payload.routeId,
    vehicleId: payload.vehicleId,
    fareProductId: payload.fareProductId,
    driverId: payload.driverId,
    departureTime: timeMatch[1],
    startDate,
    daysOfWeek: payload.repeatDays,
    durationMinutes,
    blockedSeats: payload.blockedSeats,
    notes: payload.notes,
    timezone: payload.timezone,
    status: String(payload.status || '').toLowerCase() === 'draft' ? 'draft' : 'active',
  };
}

async function create(req, res, next) {
  try {
    if (String(req.body?.departureMode || 'rolling_30_days') !== 'one_off') {
      const rule = await companyService.createScheduleRule(
        companyId(req),
        rollingSchedulePayload(req.body),
        req.session?.user?.id || 'company-admin',
      );
      if (rule.status === 'active') {
        const materialized = await materializeActiveRule(req, rule);
        flashMaterialization(req, 'Rolling departure saved.', materialized);
      } else if (req.flash) req.flash('success', 'Rolling departure saved as Draft. Activate it when you want the automatic 30-day window to begin.');
      return res.redirect('/company/schedules-fares');
    }

    const result = await companyService.createScheduleBatch(companyId(req), req.body);
    if (result.publicationDeferred?.length && req.flash) {
      const failures = [...new Set(result.publicationDeferred.flatMap((item) => item.failures || []))];
      req.flash(
        'warning',
        `${result.count} departure${result.count === 1 ? ' was' : 's were'} created safely; ${result.draftCount} remain Draft until ${failures.join(', ') || 'publication checks are completed'}.`,
      );
    }
    const suffix = result.count > 1 ? `?created=${result.count}` : '';
    return res.redirect(`/company/schedules${suffix}`);
  } catch (error) {
    return handleRuleError(req, res, next, error);
  }
}

async function update(req, res, next) {
  try {
    await companyService.updateSchedule(companyId(req), req.params.id, req.body);
    res.redirect('/company/schedules');
  } catch (error) {
    next(error);
  }
}

async function archive(req, res, next) {
  try {
    await companyService.archiveSchedule(companyId(req), req.params.id);
    res.redirect('/company/schedules');
  } catch (error) {
    next(error);
  }
}

async function publish(req, res, next) {
  try {
    await companyService.publishSchedule(companyId(req), req.params.id);
    res.redirect('/company/schedules');
  } catch (error) {
    if (error.status === 422) return res.status(422).send(error.message);
    next(error);
  }
}

async function repairInventory(req, res, next) {
  try {
    const result = await companyService.repairScheduleInventory(
      companyId(req),
      req.params.id,
      req.session?.user?.id || 'company-admin',
    );
    if (req.flash) req.flash('success', `Seat inventory repaired: ${result.seatCount} seats across ${result.segmentCount} route segments.`);
    res.redirect('/company/seat-maps');
  } catch (error) {
    if (req.flash && [409, 422].includes(Number(error.status || 0))) {
      req.flash('error', error.message);
      return res.redirect('/company/seat-maps');
    }
    return next(error);
  }
}

async function updateSeat(req, res, next) {
  try {
    await companyService.updateSeatStatus(companyId(req), req.body);
    res.redirect('/company/seat-maps');
  } catch (error) {
    next(error);
  }
}

async function transition(req, res, next) {
  try {
    await companyService.transitionSchedule(companyId(req), req.params.id, req.body, req.session?.user?.id || 'company-admin');
    res.redirect('/company/schedules-fares');
  } catch (error) {
    next(error);
  }
}

async function complete(req, res, next) {
  try {
    await companyService.completeSchedule(companyId(req), req.params.id, req.body, req.session?.user?.id || 'company-admin');
    res.redirect('/company/passenger-manifests');
  } catch (error) {
    next(error);
  }
}

async function duplicate(req, res, next) {
  try {
    await companyService.duplicateSchedule(companyId(req), req.params.id, req.body, req.session?.user?.id || 'company-admin');
    res.redirect('/company/schedules-fares');
  } catch (error) {
    next(error);
  }
}

async function createRule(req, res, next) {
  try {
    const rule = await companyService.createScheduleRule(companyId(req), req.body, req.session?.user?.id || 'company-admin');
    if (rule.status === 'active') {
      const materialized = await materializeActiveRule(req, rule);
      flashMaterialization(req, 'Recurring rule saved.', materialized);
    } else if (req.flash) req.flash('success', 'Recurring rule saved. Activate it when you want the rolling 30-day departure window to begin.');
    res.redirect('/company/schedules-fares');
  } catch (error) {
    handleRuleError(req, res, next, error);
  }
}

async function updateRule(req, res, next) {
  try {
    const rule = await companyService.updateScheduleRule(companyId(req), req.params.id, req.body, req.session?.user?.id || 'company-admin');
    if (rule.status === 'active') {
      const materialized = await materializeActiveRule(req, rule);
      flashMaterialization(req, 'Recurring rule updated.', materialized);
    }
    res.redirect('/company/schedules-fares');
  } catch (error) {
    handleRuleError(req, res, next, error);
  }
}

async function pauseRule(req, res, next) {
  try {
    await companyService.pauseScheduleRule(companyId(req), req.params.id, req.session?.user?.id || 'company-admin');
    res.redirect('/company/schedules-fares');
  } catch (error) {
    next(error);
  }
}

async function resumeRule(req, res, next) {
  try {
    const rule = await companyService.resumeScheduleRule(companyId(req), req.params.id, req.session?.user?.id || 'company-admin');
    const materialized = await materializeActiveRule(req, rule);
    flashMaterialization(req, 'Recurring rule resumed.', materialized);
    res.redirect('/company/schedules-fares');
  } catch (error) {
    handleRuleError(req, res, next, error);
  }
}

async function cancelRule(req, res, next) {
  try {
    await companyService.cancelScheduleRule(companyId(req), req.params.id, req.session?.user?.id || 'company-admin');
    res.redirect('/company/schedules-fares');
  } catch (error) {
    next(error);
  }
}

module.exports = {
  create, update, archive, publish, repairInventory, updateSeat, transition, duplicate, complete,
  createRule, updateRule, pauseRule, resumeRule, cancelRule, rollingSchedulePayload,
  materializationSummary,
};
