const express = require('express');
const dashboardController = require('../../controllers/admin/dashboardController');
const companyController = require('../../controllers/admin/companyController');
const bookingController = require('../../controllers/admin/bookingController');
const paymentController = require('../../controllers/admin/paymentController');
const promoterController = require('../../controllers/admin/promoterController');
const withdrawalController = require('../../controllers/admin/withdrawalController');
const disputeController = require('../../controllers/admin/disputeController');
const reviewController = require('../../controllers/admin/reviewController');
const promotionController = require('../../controllers/admin/promotionController');
const settingController = require('../../controllers/admin/settingController');
const partnerPipelineController = require('../../controllers/admin/partnerPipelineController');
const invitationController = require('../../controllers/admin/invitationController');
const verificationController = require('../../controllers/admin/verificationController');
const futureServiceController = require('../../controllers/admin/futureServiceController');
const masterImplementationController = require('../../controllers/admin/masterImplementationController');
const actionController = require('../../controllers/admin/actionController');
const financeController = require('../../controllers/admin/financeController');
const promoterNetworkController = require('../../controllers/promoter/networkController');
const reportController = require('../../controllers/reportController');
const { requireAuth } = require('../../middlewares/auth');
const { requireRole } = require('../../middlewares/roles');
const upload = require('../../middlewares/upload');
const { companyRules } = require('../../validators/companyValidator');
const { validateRequest } = require('../../middlewares/validate');
const router = express.Router();

router.use('/admin', requireAuth, requireRole('super_admin'));
router.use('/support', requireAuth, requireRole('super_admin', 'support_admin'));
router.use('/finance', requireAuth, requireRole('super_admin', 'finance_admin'));
router.use('/operations', requireAuth, requireRole('super_admin', 'operations_admin'));

router.get('/admin', dashboardController.index);
router.get('/support/dashboard', dashboardController.support);
router.get('/finance/dashboard', dashboardController.finance);
router.get('/operations/dashboard', dashboardController.operations);
router.get('/admin/companies', dashboardController.index);
router.get('/admin/bookings', dashboardController.index);
router.get('/admin/payments', dashboardController.index);
router.get('/admin/promoters', dashboardController.index);
router.get('/admin/withdrawals', dashboardController.index);
router.get('/admin/disputes', dashboardController.index);
router.get('/admin/refunds', dashboardController.index);
router.get('/admin/reviews', dashboardController.index);
router.get('/admin/promotions', dashboardController.index);
router.get('/admin/support', dashboardController.index);
router.get('/admin/reschedules', dashboardController.index);
router.get('/admin/settings', dashboardController.index);
router.get('/admin/future-services.json', futureServiceController.summary);
router.get('/admin/master-implementation', masterImplementationController.page);
router.get('/admin/master-implementation.json', masterImplementationController.json);
router.get('/admin/master-implementation.csv', masterImplementationController.csv);
router.get('/support/dashboard/:page', dashboardController.support);
router.get('/finance/dashboard/:page', dashboardController.finance);
router.get('/operations/dashboard/:page', dashboardController.operations);
router.get('/admin/reports/:type.csv', reportController.admin);
router.get('/admin/:page', dashboardController.index);
router.post('/admin/reports/custom', reportController.adminCustom);
router.post('/admin/companies', upload.single('imageFile'), companyRules, validateRequest, companyController.create);
router.post('/admin/companies/:slug/approve', companyController.approve);
router.post('/admin/companies/:slug/reject', companyController.reject);
router.post('/admin/companies/:slug/suspend', companyController.suspend);
router.post('/admin/leads', partnerPipelineController.createLead);
router.post('/admin/sessions', partnerPipelineController.createSession);
router.post('/admin/agreements', partnerPipelineController.createAgreement);
router.post('/admin/agreements/:id/approve', partnerPipelineController.approveAgreement);
router.post('/admin/agreements/:id/reject', partnerPipelineController.rejectAgreement);
router.post('/admin/invitations', invitationController.create);
router.post('/admin/invitations/:id/resend', invitationController.resend);
router.post('/admin/invitations/:id/revoke', invitationController.revoke);
router.post('/admin/invitations/:id/approve', invitationController.approve);
router.post('/admin/verification/:targetType/:targetId/items/:key/approve', verificationController.approveItem);
router.post('/admin/verification/:targetType/:targetId/items/:key/reject', verificationController.rejectItem);
router.post('/admin/verification/:targetType/:targetId/items/:key/waive', verificationController.waiveItem);
router.post('/admin/verification/:targetType/:targetId/activate', verificationController.activate);
router.post('/admin/verification/:targetType/:targetId/reject', verificationController.rejectTarget);
router.post('/admin/media-documents/:targetType/:targetId/:publicId/review', verificationController.reviewDocument);
router.get('/admin/api/bookings', bookingController.list);
router.get('/admin/api/payments', paymentController.list);
router.get('/admin/api/promoters', promoterController.list);
router.get('/admin/api/promoter-network', promoterNetworkController.adminPromoterSummary);
router.post('/admin/withdrawals/:id/approve', withdrawalController.approve);
router.get('/admin/api/disputes', disputeController.list);
router.post('/admin/refunds/:id/approve', disputeController.approveRefund);
router.post('/admin/refunds/:id/reject', disputeController.rejectRefund);
router.post('/admin/reviews/:id/moderate', reviewController.moderate);
router.get('/admin/api/promotions', promotionController.list);
router.post('/admin/bookings', actionController.createBooking);
router.post('/admin/listings', actionController.createListing);
router.post('/admin/promotions', promotionController.create);
router.post('/admin/notices', actionController.createNotice);
router.post('/admin/notifications', actionController.sendNotification);
router.post('/admin/customer-notes', actionController.createCustomerNote);
router.post('/admin/admin-users', actionController.inviteAdmin);
router.post('/admin/verification-tasks', actionController.createVerificationTask);
router.post('/admin/refunds', actionController.createRefund);
router.post('/admin/payouts/run', actionController.runPayout);
router.post('/admin/payments/freeze', actionController.freezePayment);
router.post('/admin/finance-rules', actionController.updateFinanceRules);
router.post('/admin/finance/release-eligible', financeController.releaseEligible);
router.post('/admin/settlements', financeController.createSettlement);
router.post('/admin/payouts/sync', financeController.syncPayouts);
router.post('/admin/payouts/batch', financeController.createPayoutBatch);
router.post('/admin/payouts/:id/review', financeController.reviewPayout);
router.post('/admin/wallet-top-ups/:id/review', financeController.reviewTopUp);
router.post('/admin/reconciliation', financeController.reconcile);
router.post('/admin/finance/statements', financeController.generateStatements);
router.post('/admin/price-rules', actionController.updatePriceRule);
router.post('/admin/templates', actionController.updateTemplate);
router.post('/admin/settings', settingController.update);
router.post('/admin/support/:id/reply', actionController.replySupport);
router.post('/admin/driver-requests/:id/approve', actionController.approveDriverRequest);
router.post('/admin/driver-requests/:id/reject', actionController.rejectDriverRequest);
router.post('/admin/internal-notes', actionController.createInternalNote);
router.post('/admin/reschedules/:id/approve', actionController.approveReschedule);
router.post('/admin/reschedules/:id/reject', actionController.rejectReschedule);
router.post('/admin/fraud-signals/:id/review', promoterNetworkController.reviewFraudSignal);

module.exports = router;
