const express = require('express');
const dashboardController = require('../../controllers/admin/dashboardController');
const companyController = require('../../controllers/admin/companyController');
const bookingController = require('../../controllers/admin/bookingController');
const paymentController = require('../../controllers/admin/paymentController');
const promoterController = require('../../controllers/admin/promoterController');
const withdrawalController = require('../../controllers/admin/withdrawalController');
const disputeController = require('../../controllers/admin/disputeController');
const reviewController = require('../../controllers/admin/reviewController');
const promotionController = require('../../controllers/admin/promotionController');
const settingController = require('../../controllers/admin/settingController');
const partnerPipelineController = require('../../controllers/admin/partnerPipelineController');
const invitationController = require('../../controllers/admin/invitationController');
const verificationController = require('../../controllers/admin/verificationController');
const actionController = require('../../controllers/admin/actionController');
const financeController = require('../../controllers/admin/financeController');
const promoterNetworkController = require('../../controllers/promoter/networkController');
const reportController = require('../../controllers/reportController');
const { requireAuth } = require('../../middlewares/auth');
const { requireRole } = require('../../middlewares/roles');
const { requirePermission } = require('../../middlewares/permissions');
const upload = require('../../middlewares/upload');
const { requireCsrfToken } = require('../../middlewares/csrf');
const { companyRules } = require('../../validators/companyValidator');
const { validateRequest } = require('../../middlewares/validate');
const { sensitiveActionLimiter } = require('../../middlewares/rateLimit');
const { rewriteAdminRedirect } = require('../../middlewares/adminRoleRedirect');
const { requirePlatformMfa } = require('../../middlewares/mfa');
const router = express.Router();

router.use('/admin', requireAuth, requireRole('super_admin'), requirePlatformMfa);
router.use('/content', requireAuth, requireRole('super_admin', 'admin', 'content_admin'), requirePlatformMfa, rewriteAdminRedirect('content'));
router.use('/support', requireAuth, requireRole('super_admin', 'admin', 'support_admin'), requirePlatformMfa, rewriteAdminRedirect('support'));
router.use('/finance', requireAuth, requireRole('super_admin', 'admin', 'finance_admin'), requirePlatformMfa, rewriteAdminRedirect('finance'));
router.use('/operations', requireAuth, requireRole('super_admin', 'admin', 'operations_admin'), requirePlatformMfa, rewriteAdminRedirect('operations'));
router.post('/admin/*', sensitiveActionLimiter);
router.post('/support/*', sensitiveActionLimiter);
router.post('/finance/*', sensitiveActionLimiter);
router.post('/operations/*', sensitiveActionLimiter);
router.post('/content/*', sensitiveActionLimiter);

router.get('/admin', dashboardController.index);
router.get('/support/dashboard', dashboardController.support);
router.get('/finance/dashboard', dashboardController.finance);
router.get('/operations/dashboard', dashboardController.operations);
router.get('/content/dashboard', dashboardController.content);
router.get('/content/dashboard/:page', dashboardController.content);

// Specialized administrator actions are exposed under their own role boundary. The
// /admin namespace remains Super Admin only, preventing specialized admins from loading
// or mutating unrelated platform data.
router.get('/support/reports/:type.csv', requirePermission('reports.view'), reportController.support);
router.post('/support/reports/custom', requirePermission('reports.view'), reportController.support);
router.post('/support/notices', requirePermission('support.manage'), actionController.createNotice);
router.post('/support/customer-notes', requirePermission('support.manage'), actionController.createCustomerNote);
router.post('/support/:id/reply', requirePermission('support.manage'), actionController.replySupport);
router.post('/support/internal-notes', requirePermission('support.manage'), actionController.createInternalNote);
router.post('/support/refunds', requirePermission('refunds.request'), actionController.createRefund);
router.post('/support/reschedules/:id/approve', requirePermission('support.manage'), actionController.approveReschedule);
router.post('/support/reschedules/:id/reject', requirePermission('support.manage'), actionController.rejectReschedule);

router.get('/finance/reports/:type.csv', requirePermission('reports.view'), reportController.finance);
router.post('/finance/reports/custom', requirePermission('reports.view'), reportController.finance);
router.post('/finance/payments/freeze', requirePermission('finance.manage'), actionController.freezePayment);
router.post('/finance/payouts/run', requirePermission('finance.manage'), actionController.runPayout);
router.post('/finance/finance-rules', requirePermission('finance.manage'), actionController.updateFinanceRules);
router.post('/finance/release-eligible', requirePermission('finance.manage'), financeController.releaseEligible);
router.post('/finance/settlements', requirePermission('finance.manage'), financeController.createSettlement);
router.post('/finance/payouts/sync', requirePermission('finance.manage'), financeController.syncPayouts);
router.post('/finance/payouts/batch', requirePermission('finance.manage'), financeController.createPayoutBatch);
router.post('/finance/payouts/:id/review', requirePermission('finance.manage'), financeController.reviewPayout);
router.post('/finance/wallet-top-ups/:id/review', requirePermission('finance.manage'), financeController.reviewTopUp);
router.post('/finance/reconciliation', requirePermission('finance.manage'), financeController.reconcile);
router.post('/finance/statements', requirePermission('finance.manage'), financeController.generateStatements);
router.post('/finance/refunds/:id/approve', requirePermission('refunds.manage'), disputeController.approveRefund);
router.post('/finance/refunds/:id/reject', requirePermission('refunds.manage'), disputeController.rejectRefund);

router.get('/operations/reports/:type.csv', requirePermission('reports.view'), reportController.operations);
router.post('/operations/reports/custom', requirePermission('reports.view'), reportController.operations);
router.post('/operations/bookings', requirePermission('operations.manage'), actionController.createBooking);
router.post('/operations/listings', requirePermission('operations.manage'), actionController.createListing);

router.get('/content/reports/:type.csv', requirePermission('reports.view'), reportController.content);
router.post('/content/reports/custom', requirePermission('reports.view'), reportController.content);
router.post('/content/listings', requirePermission('content.manage'), actionController.createListing);
router.post('/content/promotions', requirePermission('content.manage'), promotionController.create);
router.post('/content/price-rules', requirePermission('content.manage'), actionController.updatePriceRule);
router.post('/content/templates', requirePermission('content.manage'), actionController.updateTemplate);
router.post('/content/notices', requirePermission('content.manage'), actionController.createNotice);
router.post('/content/notifications', requirePermission('content.manage'), actionController.sendNotification);
router.post('/content/reviews/:id/moderate', requirePermission('content.manage'), reviewController.moderate);

router.get('/admin/companies', dashboardController.index);
router.get('/admin/bookings', dashboardController.index);
router.get('/admin/payments', dashboardController.index);
router.get('/admin/promoters', dashboardController.index);
router.get('/admin/withdrawals', dashboardController.index);
router.get('/admin/disputes', dashboardController.index);
router.get('/admin/refunds', dashboardController.index);
router.get('/admin/reviews', dashboardController.index);
router.get('/admin/promotions', dashboardController.index);
router.get('/admin/support', dashboardController.index);
router.get('/admin/reschedules', dashboardController.index);
router.get('/admin/settings', dashboardController.index);
router.get('/support/dashboard/:page', dashboardController.support);
router.get('/finance/dashboard/:page', dashboardController.finance);
router.get('/operations/dashboard/:page', dashboardController.operations);
router.get('/admin/reports/:type.csv', reportController.admin);
router.get('/admin/:page', dashboardController.index);
router.post('/admin/reports/custom', reportController.adminCustom);
router.post('/admin/companies', upload.single('imageFile'), requireCsrfToken, companyRules, validateRequest, companyController.create);
router.post('/admin/companies/:slug/commission', companyController.updateCommission);
router.post('/admin/companies/:slug/approve', companyController.approve);
router.post('/admin/companies/:slug/reject', companyController.reject);
router.post('/admin/companies/:slug/suspend', companyController.suspend);
router.post('/admin/leads', partnerPipelineController.createLead);
router.post('/admin/sessions', partnerPipelineController.createSession);
router.post('/admin/agreements', partnerPipelineController.createAgreement);
router.post('/admin/agreements/:id/approve', partnerPipelineController.approveAgreement);
router.post('/admin/agreements/:id/reject', partnerPipelineController.rejectAgreement);
router.post('/admin/invitations', invitationController.create);
router.post('/admin/invitations/:id/resend', invitationController.resend);
router.post('/admin/invitations/:id/revoke', invitationController.revoke);
router.post('/admin/invitations/:id/approve', invitationController.approve);
router.post('/admin/verification/:targetType/:targetId/items/:key/approve', verificationController.approveItem);
router.post('/admin/verification/:targetType/:targetId/items/:key/reject', verificationController.rejectItem);
router.post('/admin/verification/:targetType/:targetId/items/:key/waive', verificationController.waiveItem);
router.post('/admin/verification/:targetType/:targetId/activate', verificationController.activate);
router.post('/admin/verification/:targetType/:targetId/reject', verificationController.rejectTarget);
router.post('/admin/media-documents/:targetType/:targetId/:publicId/review', verificationController.reviewDocument);
router.get('/admin/api/bookings', bookingController.list);
router.get('/admin/api/payments', paymentController.list);
router.get('/admin/api/promoters', promoterController.list);
router.get('/admin/api/promoter-network', promoterNetworkController.adminPromoterSummary);
router.post('/admin/withdrawals/:id/approve', withdrawalController.approve);
router.get('/admin/api/disputes', disputeController.list);
router.post('/admin/refunds/:id/approve', disputeController.approveRefund);
router.post('/admin/refunds/:id/reject', disputeController.rejectRefund);
router.post('/admin/reviews/:id/moderate', reviewController.moderate);
router.get('/admin/api/promotions', promotionController.list);
router.post('/admin/bookings', actionController.createBooking);
router.post('/admin/listings', actionController.createListing);
router.post('/admin/promotions', promotionController.create);
router.post('/admin/notices', actionController.createNotice);
router.post('/admin/notifications', actionController.sendNotification);
router.post('/admin/customer-notes', actionController.createCustomerNote);
router.post('/admin/admin-users', actionController.inviteAdmin);
router.post('/admin/verification-tasks', actionController.createVerificationTask);
router.post('/admin/refunds', actionController.createRefund);
router.post('/admin/payouts/run', actionController.runPayout);
router.post('/admin/payments/freeze', actionController.freezePayment);
router.post('/admin/finance-rules', actionController.updateFinanceRules);
router.post('/admin/finance/release-eligible', financeController.releaseEligible);
router.post('/admin/settlements', financeController.createSettlement);
router.post('/admin/payouts/sync', financeController.syncPayouts);
router.post('/admin/payouts/batch', financeController.createPayoutBatch);
router.post('/admin/payouts/:id/review', financeController.reviewPayout);
router.post('/admin/wallet-top-ups/:id/review', financeController.reviewTopUp);
router.post('/admin/reconciliation', financeController.reconcile);
router.post('/admin/finance/statements', financeController.generateStatements);
router.post('/admin/price-rules', actionController.updatePriceRule);
router.post('/admin/templates', actionController.updateTemplate);
router.post('/admin/settings', settingController.update);
router.post('/admin/support/:id/reply', actionController.replySupport);
router.post('/admin/internal-notes', actionController.createInternalNote);
router.post('/admin/reschedules/:id/approve', actionController.approveReschedule);
router.post('/admin/reschedules/:id/reject', actionController.rejectReschedule);
router.post('/admin/fraud-signals/:id/review', promoterNetworkController.reviewFraudSignal);

module.exports = router;
