const express = require('express');
const dashboardController = require('../../controllers/company/dashboardController');
const listingController = require('../../controllers/company/listingController');
const routeController = require('../../controllers/company/routeController');
const vehicleController = require('../../controllers/company/vehicleController');
const scheduleController = require('../../controllers/company/scheduleController');
const fareController = require('../../controllers/company/fareController');
const addonController = require('../../controllers/company/addonController');
const employeeController = require('../../controllers/company/employeeController');
const promotionController = require('../../controllers/company/promotionController');
const analyticsController = require('../../controllers/company/analyticsController');
const mediaController = require('../../controllers/company/mediaController');
const checkinController = require('../../controllers/company/checkinController');
const qrController = require('../../controllers/company/qrController');
const actionController = require('../../controllers/company/actionController');
const onboardingController = require('../../controllers/company/onboardingController');
const verificationController = require('../../controllers/company/verificationController');
const operationsController = require('../../controllers/company/operationsController');
const hotelController = require('../../controllers/company/hotelController');
const manifestController = require('../../controllers/employee/manifestController');
const publicListingController = require('../../controllers/public/listingController');
const reportController = require('../../controllers/reportController');
const { requireAuth } = require('../../middlewares/auth');
const { requireRole } = require('../../middlewares/roles');
const upload = require('../../middlewares/upload');
const { requireCsrfToken } = require('../../middlewares/csrf');
const { enforceCompanyScope, requireVerifiedCompany, requireCompanyService, requireCompanyOwnService } = require('../../middlewares/companyAccess');
const { ticketLimiter, sensitiveActionLimiter } = require('../../middlewares/rateLimit');
const router = express.Router();

router.use('/company', requireAuth, requireRole('company_admin', 'super_admin'), enforceCompanyScope);
router.post('/company/*', sensitiveActionLimiter);

router.get('/company/dashboard', dashboardController.index);
router.get('/company/dashboard/:page', dashboardController.index);
router.get('/company/listings', dashboardController.index);
router.get('/company/routes', dashboardController.index);
router.get('/company/vehicles', dashboardController.index);
router.get('/company/schedules', dashboardController.index);
router.get('/company/rooms', dashboardController.index);
router.get('/company/bookings', dashboardController.index);
router.get('/company/checkins', dashboardController.index);
router.get('/company/employees', dashboardController.index);
router.get('/company/promotions', dashboardController.index);
router.get('/company/payouts', dashboardController.index);
router.get('/company/analytics', dashboardController.index);
router.get('/company/support', dashboardController.index);
router.get('/company/staff', dashboardController.index);
router.get('/company/driver-requests', dashboardController.index);
router.get('/company/bus-listings', dashboardController.index);
router.get('/company/routes-stops', dashboardController.index);
router.get('/company/schedules-fares', dashboardController.index);
router.get('/company/passenger-manifests', dashboardController.index);
router.get('/company/boarding-checkins', dashboardController.index);
router.get('/company/seat-maps', dashboardController.index);
router.get('/company/hotel-rooms', dashboardController.index);
router.get('/company/hotel-properties', dashboardController.index);
router.get('/company/room-types', dashboardController.index);
router.get('/company/rate-plans', dashboardController.index);
router.get('/company/room-units', dashboardController.index);
router.get('/company/room-calendar', dashboardController.index);
router.get('/company/arrivals', dashboardController.index);
router.get('/company/departures', dashboardController.index);
router.get('/company/in-house-guests', dashboardController.index);
router.get('/company/housekeeping', dashboardController.index);
router.get('/company/revenue', dashboardController.index);
router.get('/company/settlement', dashboardController.index);
router.get('/company/reports', dashboardController.index);
router.get('/company/manifests-dashboard', dashboardController.index);
router.get('/company/profile', dashboardController.index);
router.get('/company/bus-dashboard', dashboardController.index);
router.get('/company/hotel-dashboard', dashboardController.index);

router.get('/company/schedules/:scheduleId/manifest', requireCompanyService('bus'), manifestController.manifestPage);
router.get('/company/schedules/:scheduleId/manifest.csv', requireCompanyService('bus'), manifestController.manifestCsv);
router.get('/company/schedules/:scheduleId/manifest.xls', requireCompanyService('bus'), manifestController.manifestExcel);
router.get('/company/schedules/:scheduleId/manifest.pdf', requireCompanyService('bus'), manifestController.manifestPdf);
router.get('/company/tickets/:bookingRef', requireCompanyService('bus'), ticketLimiter, manifestController.ticketDetail);
router.get('/company/seats/:scheduleId/:seatNumber/ticket', ticketLimiter, requireCompanyService('bus'), manifestController.seatTicketDetail);
router.get('/company/manifests', requireCompanyService('bus'), manifestController.customerManifestPage);
router.get('/company/manifests.csv', requireCompanyService('bus'), manifestController.customerManifestCsv);
router.get('/company/manifests.xls', requireCompanyService('bus'), manifestController.customerManifestExcel);
router.get('/company/manifests.pdf', requireCompanyService('bus'), manifestController.customerManifestPdf);
router.get('/company/reports/:type.csv', reportController.company);
router.post('/company/reports/custom', reportController.companyCustom);
router.post('/company/bus-services', requireCompanyService('bus'), upload.fields([
  { name: 'listingImageFile', maxCount: 1 },
  { name: 'vehicleImageFile', maxCount: 1 },
]), requireCsrfToken, onboardingController.createBusService);
router.post('/company/listings', upload.single('imageFile'), requireCsrfToken, requireCompanyOwnService('serviceType'), listingController.create);
router.post('/company/listings/:id', upload.single('imageFile'), requireCsrfToken, requireCompanyOwnService('serviceType'), listingController.update);
router.post('/company/listings/:id/publish', listingController.publish);
router.post('/company/listings/:id/archive', listingController.archive);
router.post('/company/routes', requireCompanyService('bus'), routeController.create);
router.post('/company/routes/:id', requireCompanyService('bus'), routeController.update);
router.post('/company/routes/:id/archive', requireCompanyService('bus'), routeController.archive);
router.post('/company/routes/:id/stops', requireCompanyService('bus'), routeController.createStop);
router.post('/company/route-stops/:stopId', requireCompanyService('bus'), routeController.updateStop);
router.post('/company/route-stops/:stopId/archive', requireCompanyService('bus'), routeController.archiveStop);
router.post('/company/route-stops/:stopId/move', requireCompanyService('bus'), routeController.moveStop);
router.post('/company/vehicles', requireCompanyService('bus'), upload.single('imageFile'), requireCsrfToken, vehicleController.create);
router.post('/company/vehicles/seat-template', requireCompanyService('bus'), vehicleController.updateSeatTemplate);
router.post('/company/vehicles/:id', requireCompanyService('bus'), upload.single('imageFile'), requireCsrfToken, vehicleController.update);
router.post('/company/vehicles/:id/archive', requireCompanyService('bus'), vehicleController.archive);
router.post('/company/vehicles/:id/seats', requireCompanyService('bus'), vehicleController.updateSeats);
router.post('/company/vehicles/:id/status', requireCompanyService('bus'), vehicleController.updateStatus);
router.post('/company/fares', requireCompanyService('bus'), fareController.create);
router.post('/company/fares/:id', requireCompanyService('bus'), fareController.update);
router.post('/company/fares/:id/segments', requireCompanyService('bus'), fareController.upsertSegment);
router.post('/company/fare-segments', requireCompanyService('bus'), fareController.upsertSegmentFromBody);
router.post('/company/addons', requireCompanyService('bus', 'hotel'), addonController.create);
router.post('/company/addons/:id', requireCompanyService('bus', 'hotel'), addonController.update);
router.post('/company/addons/:id/archive', requireCompanyService('bus', 'hotel'), addonController.archive);
router.post('/company/schedules', requireCompanyService('bus'), scheduleController.create);
router.post('/company/schedule-rules', requireCompanyService('bus'), scheduleController.createRule);
router.post('/company/schedule-rules/:id/pause', requireCompanyService('bus'), scheduleController.pauseRule);
router.post('/company/schedule-rules/:id/resume', requireCompanyService('bus'), scheduleController.resumeRule);
router.post('/company/schedule-rules/:id/cancel', requireCompanyService('bus'), scheduleController.cancelRule);
router.post('/company/schedules/:id', requireCompanyService('bus'), scheduleController.update);
router.post('/company/schedules/:id/publish', requireCompanyService('bus'), scheduleController.publish);
router.post('/company/schedules/:id/status', requireCompanyService('bus'), scheduleController.transition);
router.post('/company/schedules/:id/duplicate', requireCompanyService('bus'), scheduleController.duplicate);
router.post('/company/schedules/:id/archive', requireCompanyService('bus'), scheduleController.archive);
router.post('/company/schedules/:id/complete', requireCompanyService('bus'), scheduleController.complete);
router.post('/company/seats/status', requireCompanyService('bus'), scheduleController.updateSeat);
router.post('/company/hotels/properties', requireCompanyService('hotel'), hotelController.createProperty);
router.post('/company/hotels/properties/:id', requireCompanyService('hotel'), hotelController.updateProperty);
router.post('/company/hotels/properties/:id/archive', requireCompanyService('hotel'), hotelController.archiveProperty);
router.post('/company/hotels/room-types', requireCompanyService('hotel'), hotelController.createRoomType);
router.post('/company/hotels/room-types/:id', requireCompanyService('hotel'), hotelController.updateRoomType);
router.post('/company/hotels/room-types/:id/inventory', requireCompanyService('hotel'), hotelController.setRoomTypeInventory);
router.post('/company/hotels/room-types/:id/archive', requireCompanyService('hotel'), hotelController.archiveRoomType);
router.post('/company/hotels/rate-plans', requireCompanyService('hotel'), hotelController.createRatePlan);
router.post('/company/hotels/rate-plans/:id', requireCompanyService('hotel'), hotelController.updateRatePlan);
router.post('/company/hotels/rate-plans/:id/archive', requireCompanyService('hotel'), hotelController.archiveRatePlan);
router.post('/company/hotels/room-units', requireCompanyService('hotel'), hotelController.createRoomUnits);
router.post('/company/hotels/room-units/:id', requireCompanyService('hotel'), hotelController.updateRoomUnit);
router.post('/company/hotels/room-units/:id/archive', requireCompanyService('hotel'), hotelController.archiveRoomUnit);
router.post('/company/hotels/housekeeping/:unitId', requireCompanyService('hotel'), hotelController.updateHousekeeping);
router.post('/company/hotels/inventory', requireCompanyService('hotel'), hotelController.createInventory);
router.post('/company/hotels/inventory/:id/status', requireCompanyService('hotel'), hotelController.updateInventoryStatus);
router.post('/company/hotels/inventory/:id/archive', requireCompanyService('hotel'), hotelController.archiveInventory);
router.post('/company/hotels/bookings', requireVerifiedCompany, requireCompanyService('hotel'), actionController.createBooking);
router.get('/company/hotels/bookings/:bookingRef/voucher', requireVerifiedCompany, requireCompanyService('hotel'), ticketLimiter, hotelController.voucher);
router.get('/company/hotels/bookings/:bookingRef/voucher.pdf', requireVerifiedCompany, requireCompanyService('hotel'), ticketLimiter, hotelController.voucherPdf);
router.post('/company/hotels/bookings/:bookingRef/check-in', requireVerifiedCompany, requireCompanyService('hotel'), hotelController.checkIn);
router.post('/company/hotels/bookings/:bookingRef/check-out', requireVerifiedCompany, requireCompanyService('hotel'), hotelController.checkOut);
router.post('/company/hotels/bookings/:bookingRef/no-show', requireVerifiedCompany, requireCompanyService('hotel'), hotelController.noShow);
router.get('/company/hotels/manifest', requireVerifiedCompany, requireCompanyService('hotel'), hotelController.manifest);
router.get('/company/hotels/manifest.csv', requireVerifiedCompany, requireCompanyService('hotel'), hotelController.manifestCsv);
router.get('/company/hotels/manifest.pdf', requireVerifiedCompany, requireCompanyService('hotel'), hotelController.manifestPdf);
router.get('/company/hotels/:listingId/manifest', requireVerifiedCompany, requireCompanyService('hotel'), hotelController.manifest);
router.get('/company/hotels/:listingId/manifest.csv', requireVerifiedCompany, requireCompanyService('hotel'), hotelController.manifestCsv);
router.get('/company/hotels/:listingId/manifest.pdf', requireVerifiedCompany, requireCompanyService('hotel'), hotelController.manifestPdf);
router.get('/company/bookings/:bookingRef/qr.svg', qrController.bookingQr);
router.post('/company/scanner/lookup', requireVerifiedCompany, requireCompanyService('bus'), checkinController.lookup);
router.post('/company/scanner/validate', requireVerifiedCompany, requireCompanyService('bus'), checkinController.checkIn);
router.post('/company/scanner/no-show', requireVerifiedCompany, requireCompanyService('bus'), checkinController.noShow);
router.post('/company/checkins', requireVerifiedCompany, requireCompanyService('bus'), checkinController.checkIn);
router.post('/company/bookings', requireVerifiedCompany, actionController.createBooking);
router.post('/company/payments', requireVerifiedCompany, actionController.recordPayment);
router.post('/company/bookings/:bookingRef/check-in', requireVerifiedCompany, requireCompanyService('bus'), checkinController.checkIn);
router.post('/company/bookings/:bookingRef/no-show', requireVerifiedCompany, requireCompanyService('bus'), checkinController.noShow);
router.post('/company/verification', verificationController.submitCompany);
router.post('/company/drivers/:id/verification', requireCompanyService('bus'), verificationController.submitDriver);
router.post('/company/media', upload.single('imageFile'), requireCsrfToken, mediaController.upload);
router.post('/company/media/delete', mediaController.destroy);
router.post('/company/branches', operationsController.createBranch);
router.post('/company/policies', operationsController.createPolicy);
router.post('/company/employees/invite', requireVerifiedCompany, employeeController.invite);
router.post('/company/driver-requests', requireVerifiedCompany, requireCompanyService('bus'), actionController.createDriverRequest);
router.post('/company/staff/:id/role', operationsController.updateStaffRole);
router.post('/company/drivers/:id/profile', requireVerifiedCompany, operationsController.updateDriverProfile);
router.post('/company/drivers/:id/activate', requireVerifiedCompany, requireCompanyService('bus'), operationsController.activateDriver);
router.post('/company/drivers/:id/assign', requireVerifiedCompany, operationsController.assignDriver);
router.post('/company/promotions', promotionController.create);
router.post('/company/settings', actionController.updateSettings);
router.post('/company/payouts', requireVerifiedCompany, actionController.requestPayout);
router.post('/company/support/notices', actionController.createNotice);
router.post('/company/support/:id', actionController.updateSupport);
router.post('/company/reviews/:id/reply', actionController.replyToReview);
router.get('/company/api/analytics', analyticsController.summary);

module.exports = router;
