const express = require('express');
const dashboardController = require('../../controllers/company/dashboardController');
const listingController = require('../../controllers/company/listingController');
const routeController = require('../../controllers/company/routeController');
const vehicleController = require('../../controllers/company/vehicleController');
const scheduleController = require('../../controllers/company/scheduleController');
const roomController = require('../../controllers/company/roomController');
const employeeController = require('../../controllers/company/employeeController');
const promotionController = require('../../controllers/company/promotionController');
const analyticsController = require('../../controllers/company/analyticsController');
const mediaController = require('../../controllers/company/mediaController');
const checkinController = require('../../controllers/company/checkinController');
const qrController = require('../../controllers/company/qrController');
const actionController = require('../../controllers/company/actionController');
const publicListingController = require('../../controllers/public/listingController');
const billingController = require('../../controllers/public/billingController');
const reportController = require('../../controllers/reportController');
const { requireAuth } = require('../../middlewares/auth');
const { requireRole } = require('../../middlewares/roles');
const { upgradeRules } = require('../../validators/billingValidator');
const { validateRequest } = require('../../middlewares/validate');
const upload = require('../../middlewares/upload');
const router = express.Router();

router.use('/company', requireAuth, requireRole('company_admin', 'super_admin'));

router.get('/company/dashboard', dashboardController.index);
router.get('/company/listings', dashboardController.index);
router.get('/company/routes', dashboardController.index);
router.get('/company/vehicles', dashboardController.index);
router.get('/company/schedules', dashboardController.index);
router.get('/company/rooms', dashboardController.index);
router.get('/company/bookings', dashboardController.index);
router.get('/company/checkins', dashboardController.index);
router.get('/company/employees', dashboardController.index);
router.get('/company/promotions', dashboardController.index);
router.get('/company/analytics', dashboardController.index);
router.get('/company/profile', (req, res, next) => {
  const company = req.session?.user?.companyId ? require('../../services/data/demoStore').findCompany(req.session.user.companyId) : null;
  req.params.slug = company?.slug || req.session?.user?.companySlug || 'classic-express';
  return publicListingController.companyProfile(req, res, next);
});
router.get('/company/billing', billingController.renderCompanyBilling);
router.get('/company/reports/:type.csv', reportController.company);
router.post('/company/reports/custom', reportController.companyCustom);
router.post('/company/listings', upload.single('imageFile'), listingController.create);
router.post('/company/listings/:id', upload.single('imageFile'), listingController.update);
router.post('/company/listings/:id/publish', listingController.publish);
router.post('/company/listings/:id/archive', listingController.archive);
router.post('/company/routes', routeController.create);
router.post('/company/routes/:id', routeController.update);
router.post('/company/routes/:id/archive', routeController.archive);
router.post('/company/vehicles', upload.single('imageFile'), vehicleController.create);
router.post('/company/vehicles/:id', upload.single('imageFile'), vehicleController.update);
router.post('/company/vehicles/:id/archive', vehicleController.archive);
router.post('/company/schedules', scheduleController.create);
router.post('/company/schedules/:id', scheduleController.update);
router.post('/company/schedules/:id/archive', scheduleController.archive);
router.post('/company/seats/status', scheduleController.updateSeat);
router.post('/company/rooms', upload.single('imageFile'), roomController.create);
router.post('/company/rooms/:id/inventory', upload.single('imageFile'), roomController.updateInventory);
router.post('/company/rooms/:id/archive', roomController.archive);
router.get('/company/bookings/:bookingRef/qr.svg', qrController.bookingQr);
router.post('/company/scanner/lookup', checkinController.lookup);
router.post('/company/scanner/validate', checkinController.checkIn);
router.post('/company/scanner/no-show', checkinController.noShow);
router.post('/company/checkins', checkinController.checkIn);
router.post('/company/bookings', actionController.createBooking);
router.post('/company/bookings/:bookingRef/check-in', checkinController.checkIn);
router.post('/company/bookings/:bookingRef/no-show', checkinController.noShow);
router.post('/company/media', upload.single('imageFile'), mediaController.upload);
router.post('/company/employees/invite', employeeController.invite);
router.post('/company/promotions', promotionController.create);
router.post('/company/settings', actionController.updateSettings);
router.post('/company/billing/upgrade', upgradeRules, validateRequest, billingController.createUpgrade);
router.post('/company/payouts', actionController.requestPayout);
router.post('/company/support/notices', actionController.createNotice);
router.post('/company/support/:id', actionController.updateSupport);
router.post('/company/reviews/:id/reply', actionController.replyToReview);
router.get('/company/api/analytics', analyticsController.summary);

module.exports = router;
