const express = require('express');
const dashboardController = require('../../controllers/company/dashboardController');
const listingController = require('../../controllers/company/listingController');
const routeController = require('../../controllers/company/routeController');
const vehicleController = require('../../controllers/company/vehicleController');
const scheduleController = require('../../controllers/company/scheduleController');
const roomController = require('../../controllers/company/roomController');
const employeeController = require('../../controllers/company/employeeController');
const promotionController = require('../../controllers/company/promotionController');
const analyticsController = require('../../controllers/company/analyticsController');
const mediaController = require('../../controllers/company/mediaController');
const checkinController = require('../../controllers/company/checkinController');
const qrController = require('../../controllers/company/qrController');
const actionController = require('../../controllers/company/actionController');
const operationsController = require('../../controllers/company/operationsController');
const hotelController = require('../../controllers/company/hotelController');
const manifestController = require('../../controllers/employee/manifestController');
const publicListingController = require('../../controllers/public/listingController');
const billingController = require('../../controllers/public/billingController');
const reportController = require('../../controllers/reportController');
const { requireAuth } = require('../../middlewares/auth');
const { requireRole } = require('../../middlewares/roles');
const { upgradeRules } = require('../../validators/billingValidator');
const { validateRequest } = require('../../middlewares/validate');
const upload = require('../../middlewares/upload');
const { enforceCompanyScope, requireCompanyService, requireCompanyOwnService } = require('../../middlewares/companyAccess');
const { ticketLimiter } = require('../../middlewares/rateLimit');
const router = express.Router();

router.use('/company', requireAuth, requireRole('company_admin', 'super_admin'), enforceCompanyScope);

router.get('/company/dashboard', dashboardController.index);
router.get('/company/dashboard/:page', dashboardController.index);
router.get('/company/listings', dashboardController.index);
router.get('/company/routes', dashboardController.index);
router.get('/company/vehicles', dashboardController.index);
router.get('/company/schedules', dashboardController.index);
router.get('/company/rooms', dashboardController.index);
router.get('/company/bookings', dashboardController.index);
router.get('/company/checkins', dashboardController.index);
router.get('/company/employees', dashboardController.index);
router.get('/company/promotions', dashboardController.index);
router.get('/company/payouts', dashboardController.index);
router.get('/company/analytics', dashboardController.index);
router.get('/company/support', dashboardController.index);
router.get('/company/staff', dashboardController.index);
router.get('/company/driver-requests', dashboardController.index);
router.get('/company/bus-listings', dashboardController.index);
router.get('/company/routes-stops', dashboardController.index);
router.get('/company/schedules-fares', dashboardController.index);
router.get('/company/passenger-manifests', dashboardController.index);
router.get('/company/boarding-checkins', dashboardController.index);
router.get('/company/seat-maps', dashboardController.index);
router.get('/company/hotel-rooms', dashboardController.index);
router.get('/company/hotel-properties', dashboardController.index);
router.get('/company/room-types', dashboardController.index);
router.get('/company/room-units', dashboardController.index);
router.get('/company/room-calendar', dashboardController.index);
router.get('/company/arrivals', dashboardController.index);
router.get('/company/departures', dashboardController.index);
router.get('/company/in-house-guests', dashboardController.index);
router.get('/company/housekeeping', dashboardController.index);
router.get('/company/revenue', dashboardController.index);
router.get('/company/settlement', dashboardController.index);
router.get('/company/reports', dashboardController.index);
router.get('/company/manifests-dashboard', dashboardController.index);
router.get('/company/profile', dashboardController.index);
router.get('/company/bus-dashboard', dashboardController.index);
router.get('/company/hotel-dashboard', dashboardController.index);
router.get('/company/flight-dashboard', dashboardController.index);
router.get('/company/train-dashboard', dashboardController.index);
router.get('/company/tour-dashboard', dashboardController.index);
router.get('/company/car-rental-dashboard', dashboardController.index);
router.get('/company/event-dashboard', dashboardController.index);
router.get('/company/cargo-dashboard', dashboardController.index);
router.get('/company/insurance-dashboard', dashboardController.index);
router.get('/company/corporate-dashboard', dashboardController.index);
router.get('/company/loyalty-dashboard', dashboardController.index);

router.get('/company/billing', billingController.renderCompanyBilling);
router.get('/company/schedules/:scheduleId/manifest', requireCompanyService('bus', 'train', 'flight', 'cargo'), manifestController.manifestPage);
router.get('/company/schedules/:scheduleId/manifest.csv', requireCompanyService('bus', 'train', 'flight', 'cargo'), manifestController.manifestCsv);
router.get('/company/schedules/:scheduleId/manifest.xls', requireCompanyService('bus', 'train', 'flight', 'cargo'), manifestController.manifestExcel);
router.get('/company/schedules/:scheduleId/manifest.pdf', requireCompanyService('bus', 'train', 'flight', 'cargo'), manifestController.manifestPdf);
router.get('/company/tickets/:bookingRef', ticketLimiter, manifestController.ticketDetail);
router.get('/company/seats/:scheduleId/:seatNumber/ticket', ticketLimiter, requireCompanyService('bus', 'train', 'flight', 'event'), manifestController.seatTicketDetail);
router.get('/company/manifests', manifestController.customerManifestPage);
router.get('/company/manifests.csv', manifestController.customerManifestCsv);
router.get('/company/manifests.xls', manifestController.customerManifestExcel);
router.get('/company/manifests.pdf', manifestController.customerManifestPdf);
router.get('/company/reports/:type.csv', reportController.company);
router.post('/company/reports/custom', reportController.companyCustom);
router.post('/company/listings', requireCompanyOwnService('serviceType'), upload.single('imageFile'), listingController.create);
router.post('/company/listings/:id', requireCompanyOwnService('serviceType'), upload.single('imageFile'), listingController.update);
router.post('/company/listings/:id/publish', listingController.publish);
router.post('/company/listings/:id/archive', listingController.archive);
router.post('/company/routes', requireCompanyService('bus', 'flight', 'train', 'cargo'), routeController.create);
router.post('/company/routes/:id', requireCompanyService('bus', 'flight', 'train', 'cargo'), routeController.update);
router.post('/company/routes/:id/archive', requireCompanyService('bus', 'flight', 'train', 'cargo'), routeController.archive);
router.post('/company/routes/:id/stops', requireCompanyService('bus', 'flight', 'train', 'cargo'), routeController.createStop);
router.post('/company/route-stops/:stopId', requireCompanyService('bus', 'flight', 'train', 'cargo'), routeController.updateStop);
router.post('/company/route-stops/:stopId/archive', requireCompanyService('bus', 'flight', 'train', 'cargo'), routeController.archiveStop);
router.post('/company/route-stops/:stopId/move', requireCompanyService('bus', 'flight', 'train', 'cargo'), routeController.moveStop);
router.post('/company/vehicles', requireCompanyService('bus', 'flight', 'train', 'car_rental', 'cargo'), upload.single('imageFile'), vehicleController.create);
router.post('/company/vehicles/seat-template', requireCompanyService('bus', 'flight', 'train', 'car_rental', 'cargo'), vehicleController.updateSeatTemplate);
router.post('/company/vehicles/:id', requireCompanyService('bus', 'flight', 'train', 'car_rental', 'cargo'), upload.single('imageFile'), vehicleController.update);
router.post('/company/vehicles/:id/archive', requireCompanyService('bus', 'flight', 'train', 'car_rental', 'cargo'), vehicleController.archive);
router.post('/company/vehicles/:id/seats', requireCompanyService('bus', 'flight', 'train', 'car_rental', 'cargo'), vehicleController.updateSeats);
router.post('/company/vehicles/:id/status', requireCompanyService('bus', 'flight', 'train', 'car_rental', 'cargo'), vehicleController.updateStatus);
router.post('/company/schedules', requireCompanyService('bus', 'flight', 'train', 'tour', 'car_rental', 'event', 'cargo'), scheduleController.create);
router.post('/company/schedules/:id', requireCompanyService('bus', 'flight', 'train', 'tour', 'car_rental', 'event', 'cargo'), scheduleController.update);
router.post('/company/schedules/:id/publish', requireCompanyService('bus', 'flight', 'train', 'tour', 'car_rental', 'event', 'cargo'), scheduleController.publish);
router.post('/company/schedules/:id/status', requireCompanyService('bus', 'flight', 'train', 'tour', 'car_rental', 'event', 'cargo'), scheduleController.transition);
router.post('/company/schedules/:id/duplicate', requireCompanyService('bus', 'flight', 'train', 'tour', 'car_rental', 'event', 'cargo'), scheduleController.duplicate);
router.post('/company/schedules/:id/archive', requireCompanyService('bus', 'flight', 'train', 'tour', 'car_rental', 'event', 'cargo'), scheduleController.archive);
router.post('/company/schedules/:id/complete', requireCompanyService('bus', 'flight', 'train', 'tour', 'car_rental', 'event', 'cargo'), scheduleController.complete);
router.post('/company/seats/status', requireCompanyService('bus', 'flight', 'train', 'event'), scheduleController.updateSeat);
router.post('/company/rooms', upload.single('imageFile'), roomController.create);
router.post('/company/rooms/:id/inventory', upload.single('imageFile'), roomController.updateInventory);
router.post('/company/rooms/:id/archive', roomController.archive);
router.post('/company/hotels/properties', requireCompanyService('hotel'), hotelController.createProperty);
router.post('/company/hotels/properties/:id', requireCompanyService('hotel'), hotelController.updateProperty);
router.post('/company/hotels/properties/:id/archive', requireCompanyService('hotel'), hotelController.archiveProperty);
router.post('/company/hotels/room-types', requireCompanyService('hotel'), hotelController.createRoomType);
router.post('/company/hotels/room-types/:id', requireCompanyService('hotel'), hotelController.updateRoomType);
router.post('/company/hotels/room-types/:id/archive', requireCompanyService('hotel'), hotelController.archiveRoomType);
router.post('/company/hotels/room-units', requireCompanyService('hotel'), hotelController.createRoomUnits);
router.post('/company/hotels/room-units/:id', requireCompanyService('hotel'), hotelController.updateRoomUnit);
router.post('/company/hotels/room-units/:id/archive', requireCompanyService('hotel'), hotelController.archiveRoomUnit);
router.post('/company/hotels/housekeeping/:unitId', requireCompanyService('hotel'), hotelController.updateHousekeeping);
router.post('/company/hotels/inventory', requireCompanyService('hotel'), hotelController.createInventory);
router.post('/company/hotels/inventory/:id/status', requireCompanyService('hotel'), hotelController.updateInventoryStatus);
router.post('/company/hotels/inventory/:id/archive', requireCompanyService('hotel'), hotelController.archiveInventory);
router.post('/company/hotels/bookings', requireCompanyService('hotel'), actionController.createBooking);
router.post('/company/hotels/bookings/:bookingRef/check-in', requireCompanyService('hotel'), hotelController.checkIn);
router.post('/company/hotels/bookings/:bookingRef/check-out', requireCompanyService('hotel'), hotelController.checkOut);
router.get('/company/hotels/:listingId/manifest', requireCompanyService('hotel'), hotelController.manifest);
router.get('/company/hotels/:listingId/manifest.csv', requireCompanyService('hotel'), hotelController.manifestCsv);
router.get('/company/hotels/:listingId/manifest.pdf', requireCompanyService('hotel'), hotelController.manifestPdf);
router.get('/company/bookings/:bookingRef/qr.svg', qrController.bookingQr);
router.post('/company/scanner/lookup', checkinController.lookup);
router.post('/company/scanner/validate', checkinController.checkIn);
router.post('/company/scanner/no-show', checkinController.noShow);
router.post('/company/checkins', checkinController.checkIn);
router.post('/company/bookings', actionController.createBooking);
router.post('/company/bookings/:bookingRef/check-in', checkinController.checkIn);
router.post('/company/bookings/:bookingRef/no-show', checkinController.noShow);
router.post('/company/media', upload.single('imageFile'), mediaController.upload);
router.post('/company/media/delete', mediaController.destroy);
router.post('/company/branches', operationsController.createBranch);
router.post('/company/policies', operationsController.createPolicy);
router.post('/company/employees/invite', employeeController.invite);
router.post('/company/driver-requests', requireCompanyService('bus', 'train', 'flight', 'cargo', 'car_rental'), actionController.createDriverRequest);
router.post('/company/staff/:id/role', operationsController.updateStaffRole);
router.post('/company/drivers/:id/profile', operationsController.updateDriverProfile);
router.post('/company/drivers/:id/assign', operationsController.assignDriver);
router.post('/company/promotions', promotionController.create);
router.post('/company/settings', actionController.updateSettings);
router.post('/company/billing/upgrade', upgradeRules, validateRequest, billingController.createUpgrade);
router.post('/company/payouts', actionController.requestPayout);
router.post('/company/support/notices', actionController.createNotice);
router.post('/company/support/:id', actionController.updateSupport);
router.post('/company/reviews/:id/reply', actionController.replyToReview);
router.get('/company/api/analytics', analyticsController.summary);

module.exports = router;
