const express = require('express');
const dashboardController = require('../../controllers/employee/dashboardController');
const scannerController = require('../../controllers/employee/scannerController');
const checkinController = require('../../controllers/employee/checkinController');
const actionController = require('../../controllers/employee/actionController');
const manifestController = require('../../controllers/employee/manifestController');
const driverController = require('../../controllers/employee/driverController');
const companyHotelController = require('../../controllers/company/hotelController');
const reportController = require('../../controllers/reportController');
const { requireAuth } = require('../../middlewares/auth');
const { requireRole } = require('../../middlewares/roles');
const { enforceCompanyScope, requireVerifiedCompany, requireOperationalDriver, requireCompanyService } = require('../../middlewares/companyAccess');
const { requirePermission } = require('../../middlewares/permissions');
const { ticketLimiter, sensitiveActionLimiter } = require('../../middlewares/rateLimit');
const router = express.Router();

router.use('/employee', requireAuth, requireRole('company_employee', 'company_admin', 'super_admin'), enforceCompanyScope);
router.use('/driver', requireAuth, requireRole('driver', 'super_admin'), enforceCompanyScope, requireCompanyService('bus'), requireOperationalDriver);
router.post('/employee/*', sensitiveActionLimiter);
router.post('/driver/*', sensitiveActionLimiter);

router.get('/employee/dashboard', dashboardController.index);
router.get('/employee/dashboard/:page', dashboardController.index);
router.get('/employee/reports/:type.csv', requireVerifiedCompany, requirePermission('reports.view'), reportController.employee);
router.post('/employee/scanner/lookup', requireVerifiedCompany, requireCompanyService('bus'), requirePermission('booking.view', 'checkin.scan'), scannerController.lookup);
router.post('/employee/scanner/validate', requireVerifiedCompany, requireCompanyService('bus'), requirePermission('checkin.manage', 'checkin.scan'), scannerController.validate);
router.post('/employee/scanner/no-show', requireVerifiedCompany, requireCompanyService('bus'), requirePermission('checkin.no_show'), scannerController.noShow);
router.post('/employee/bookings/:bookingRef/check-in', requireVerifiedCompany, requireCompanyService('bus'), requirePermission('checkin.manage'), checkinController.checkIn);
router.post('/employee/bookings/:bookingRef/no-show', requireVerifiedCompany, requireCompanyService('bus'), requirePermission('checkin.no_show'), checkinController.noShow);
router.get('/employee/hotels/bookings/:bookingRef/voucher', requireVerifiedCompany, requireCompanyService('hotel'), requirePermission('booking.view', 'checkin.manage', 'manifest.view'), ticketLimiter, companyHotelController.voucher);
router.get('/employee/hotels/bookings/:bookingRef/voucher.pdf', requireVerifiedCompany, requireCompanyService('hotel'), requirePermission('booking.view', 'checkin.manage', 'manifest.view'), ticketLimiter, companyHotelController.voucherPdf);
router.post('/employee/hotels/bookings/:bookingRef/check-in', requireVerifiedCompany, requireCompanyService('hotel'), requirePermission('checkin.manage'), checkinController.hotelCheckIn);
router.post('/employee/hotels/bookings/:bookingRef/check-out', requireVerifiedCompany, requireCompanyService('hotel'), requirePermission('checkin.manage'), checkinController.hotelCheckOut);
router.post('/employee/hotels/bookings/:bookingRef/no-show', requireVerifiedCompany, requireCompanyService('hotel'), requirePermission('checkin.no_show'), checkinController.hotelNoShow);
router.get('/employee/hotels/manifest', requireVerifiedCompany, requireCompanyService('hotel'), requirePermission('manifest.view'), companyHotelController.manifest);
router.get('/employee/hotels/manifest.csv', requireVerifiedCompany, requireCompanyService('hotel'), requirePermission('manifest.view'), companyHotelController.manifestCsv);
router.get('/employee/hotels/manifest.pdf', requireVerifiedCompany, requireCompanyService('hotel'), requirePermission('manifest.view'), companyHotelController.manifestPdf);
router.get('/employee/hotels/:listingId/manifest', requireVerifiedCompany, requireCompanyService('hotel'), requirePermission('manifest.view'), companyHotelController.manifest);
router.get('/employee/hotels/:listingId/manifest.csv', requireVerifiedCompany, requireCompanyService('hotel'), requirePermission('manifest.view'), companyHotelController.manifestCsv);
router.get('/employee/hotels/:listingId/manifest.pdf', requireVerifiedCompany, requireCompanyService('hotel'), requirePermission('manifest.view'), companyHotelController.manifestPdf);
router.get('/employee/manifests', requireVerifiedCompany, requireCompanyService('bus'), requirePermission('manifest.view'), manifestController.customerManifestPage);
router.get('/employee/manifests.csv', requireVerifiedCompany, requireCompanyService('bus'), requirePermission('manifest.view'), manifestController.customerManifestCsv);
router.get('/employee/manifests.xls', requireVerifiedCompany, requireCompanyService('bus'), requirePermission('manifest.view'), manifestController.customerManifestExcel);
router.get('/employee/manifests.pdf', requireVerifiedCompany, requireCompanyService('bus'), requirePermission('manifest.view'), manifestController.customerManifestPdf);
router.post('/employee/bookings', requireVerifiedCompany, requirePermission('booking.create_manual'), actionController.createBooking);
router.post('/employee/inventory', requireVerifiedCompany, requirePermission('inventory.update'), actionController.updateInventory);
router.post('/employee/schedules/delay', requireVerifiedCompany, requirePermission('schedule.delay_notice'), actionController.sendDelayNotice);
router.post('/employee/payments', requireVerifiedCompany, requirePermission('payment.record'), actionController.recordPayment);
router.post('/employee/refunds', requireVerifiedCompany, requirePermission('refund.request'), actionController.requestRefund);
router.post('/employee/support/notice', requirePermission('support.manage'), actionController.createSupportNotice);
router.post('/employee/support/customer-note', requirePermission('customer.note', 'support.note'), actionController.createCustomerNote);
router.post('/employee/support/:id', requirePermission('support.manage'), actionController.updateSupport);
router.post('/employee/handovers', requireVerifiedCompany, requirePermission('handover.create'), actionController.createHandover);
router.post('/employee/profile', requirePermission('profile.update'), actionController.updateProfile);
router.post('/employee/reports/custom', requireVerifiedCompany, requirePermission('reports.view'), reportController.employeeCustom);

router.get('/driver/dashboard', driverController.driverDashboard);
router.get('/driver/dashboard/:page', driverController.driverDashboard);
router.get('/driver/schedules/:scheduleId/manifest', requireVerifiedCompany, manifestController.manifestPage);
router.get('/driver/schedules/:scheduleId/manifest.csv', requireVerifiedCompany, manifestController.manifestCsv);
router.get('/driver/schedules/:scheduleId/manifest.xls', requireVerifiedCompany, manifestController.manifestExcel);
router.get('/driver/schedules/:scheduleId/manifest.pdf', requireVerifiedCompany, manifestController.manifestPdf);
router.get('/driver/tickets/:bookingRef', requireVerifiedCompany, ticketLimiter, manifestController.ticketDetail);
router.get('/driver/seats/:scheduleId/:seatNumber/ticket', requireVerifiedCompany, ticketLimiter, manifestController.seatTicketDetail);
router.post('/driver/trips/:scheduleId/status', requireVerifiedCompany, driverController.updateTripStatus);
router.post('/driver/incidents', requireVerifiedCompany, driverController.createIncident);
router.post('/driver/bookings/:bookingRef/check-in-assist', requireVerifiedCompany, driverController.bookingAssist);

module.exports = router;
