const express = require('express');
const paymentController = require('../../controllers/api/paymentController');
const paymentService = require('../../services/payment/paymentService');
const { paymentLimiter } = require('../../middlewares/rateLimit');
const { requireApiAuth } = require('../../middlewares/apiAuth');
const { paymentRules } = require('../../validators/paymentValidator');
const { validateRequest } = require('../../middlewares/validate');
const router = express.Router();
router.get('/providers', (req, res) => res.json({ providers: paymentService.providerSummary() }));
router.post('/initiate', requireApiAuth, paymentLimiter, paymentRules, validateRequest, paymentController.initiate);
router.post('/mock/checkout', requireApiAuth, paymentLimiter, paymentRules, validateRequest, paymentController.initiate);
module.exports = router;
