const express = require('express');
const upload = require('../../middlewares/upload');
const { requireCsrfToken } = require('../../middlewares/csrf');
const uploadController = require('../../controllers/api/uploadController');
const { requireApiAuth, requireApiRole } = require('../../middlewares/apiAuth');
const { requirePlatformMfa } = require('../../middlewares/mfa');
const { sensitiveActionLimiter } = require('../../middlewares/rateLimit');
const router = express.Router();
const canUploadMedia = requireApiRole('super_admin', 'admin', 'content_admin', 'company_admin');
router.use(requireApiAuth, requirePlatformMfa);
router.post('/', sensitiveActionLimiter, canUploadMedia, upload.single('file'), requireCsrfToken, uploadController.upload);
router.post('/delete', sensitiveActionLimiter, canUploadMedia, uploadController.destroy);
router.post('/signature', sensitiveActionLimiter, canUploadMedia, uploadController.signature);
module.exports = router;
