const acceptanceMatrix = [
  {
    id: 'N-01',
    criterion: 'Super Admin creates lead, records session/agreement, and sends company invite.',
    section: 'A',
    evidence: ['tests/integration/onboardingAComplete.test.js'],
    backend: ['partner leads', 'discovery sessions', 'agreements', 'invitations'],
    frontend: ['public partner form', 'admin sessions/agreements/invitations pages'],
  },
  {
    id: 'N-02',
    criterion: 'Company accepts invite, sets up account, uploads documents, and waits for verification.',
    section: 'A',
    evidence: ['tests/integration/onboardingAComplete.test.js'],
    backend: ['invite acceptance', 'user/company creation', 'verification review'],
    frontend: ['invite acceptance page'],
  },
  {
    id: 'N-03',
    criterion: 'Super Admin verifies company; company can now publish inventory.',
    section: 'A/C',
    evidence: ['tests/integration/onboardingAComplete.test.js', 'tests/integration/busOperationsC.test.js'],
    backend: ['verification checklist', 'company activation', 'schedule publish gate'],
    frontend: ['admin verification action', 'company schedule publish action'],
  },
  {
    id: 'N-04',
    criterion: 'Super Admin invites driver or approves company driver request; driver accepts and sees assigned trips.',
    section: 'A/B',
    evidence: ['tests/integration/onboardingAComplete.test.js', 'tests/integration/companyDriverOperationsB.test.js'],
    backend: ['driver invitation', 'driver verification', 'driver assignment'],
    frontend: ['driver dashboard'],
  },
  {
    id: 'N-05',
    criterion: 'Company creates route, vehicle, seat map, schedule, fare, and driver assignment.',
    section: 'B/C',
    evidence: ['tests/integration/companyDriverOperationsB.test.js', 'tests/integration/busOperationsC.test.js'],
    backend: ['routes', 'vehicles', 'seats', 'schedules', 'driver assignments'],
    frontend: ['company dashboard setup forms'],
  },
  {
    id: 'N-06',
    criterion: 'Customer books one-way bus ticket.',
    section: 'C/G/I',
    evidence: ['tests/integration/bookingFlow.test.js', 'tests/integration/ticketQrCheckinG.test.js', 'tests/integration/financeWalletSettlementI.test.js'],
    backend: ['booking engine', 'ticket legs', 'payment/finance records'],
    frontend: ['public booking and ticket pages'],
  },
  {
    id: 'N-07',
    criterion: 'Customer books round-trip/two-way bus ticket.',
    section: 'C/G',
    evidence: ['tests/integration/busOperationsC.test.js', 'tests/integration/ticketQrCheckinG.test.js'],
    backend: ['booking legs', 'return leg ticket records'],
    frontend: ['bus booking checkout'],
  },
  {
    id: 'N-08',
    criterion: 'Customer buys multiple seats/tickets for multiple passengers in one checkout.',
    section: 'C/E/F/G',
    evidence: ['tests/integration/busOperationsC.test.js', 'tests/integration/multiServiceCartE.test.js', 'tests/integration/customerPassengerManifestF.test.js'],
    backend: ['multi-seat booking', 'passenger records', 'cart checkout'],
    frontend: ['cart checkout page', 'manifest page'],
  },
  {
    id: 'N-09',
    criterion: 'Customer books hotel room and multiple rooms.',
    section: 'D/E',
    evidence: ['tests/integration/hotelOperationsD.test.js', 'tests/integration/multiServiceCartE.test.js'],
    backend: ['room types', 'room units', 'night inventory', 'hotel booking'],
    frontend: ['hotel booking and manifest pages'],
  },
  {
    id: 'N-10',
    criterion: 'Seat/room hold expires and inventory returns to available.',
    section: 'C/D/E',
    evidence: ['tests/integration/busOperationsC.test.js', 'tests/integration/hotelOperationsD.test.js', 'tests/integration/multiServiceCartE.test.js'],
    backend: ['hold/recovery state', 'seat and room inventory release'],
    frontend: ['checkout recovery page'],
  },
  {
    id: 'N-11',
    criterion: 'Booked seat appears on visual seat map; employee clicks it and opens ticket detail.',
    section: 'F/G',
    evidence: ['tests/integration/customerPassengerManifestF.test.js', 'tests/integration/ticketQrCheckinG.test.js'],
    backend: ['seat map', 'ticket lookup by seat'],
    frontend: ['driver/company ticket detail pages'],
  },
  {
    id: 'N-12',
    criterion: 'Route/vehicle/customer manifest page prints cleanly and exports PDF/CSV.',
    section: 'F',
    evidence: ['tests/integration/customerPassengerManifestF.test.js', 'tests/integration/driverManifestPrint.test.js'],
    backend: ['manifest service', 'CSV/PDF/XLS exports'],
    frontend: ['print-ready manifest pages'],
  },
  {
    id: 'N-13',
    criterion: 'Payment webhook success creates tickets, receipts, notifications, ledger entries, and commissions.',
    section: 'G/I/M',
    evidence: ['tests/integration/bookingFlow.test.js', 'tests/integration/financeWalletSettlementI.test.js', 'tests/integration/securityReliabilityM.test.js'],
    backend: ['payment webhook', 'ticket issue', 'receipt/invoice', 'ledger/commission'],
    frontend: ['ticket/receipt visibility'],
  },
  {
    id: 'N-14',
    criterion: 'QR scan checks in the customer once and rejects a second scan.',
    section: 'G/M',
    evidence: ['tests/integration/ticketQrCheckinG.test.js', 'tests/integration/securityReliabilityM.test.js'],
    backend: ['one-time QR validation', 'scan audit', 'rate limit'],
    frontend: ['scanner endpoint/page'],
  },
  {
    id: 'N-15',
    criterion: 'Driver/employee manifest updates after check-in and no-show.',
    section: 'F/G',
    evidence: ['tests/integration/customerPassengerManifestF.test.js', 'tests/integration/ticketQrCheckinG.test.js'],
    backend: ['check-in state', 'no-show state', 'manifest refresh'],
    frontend: ['driver manifest pages'],
  },
  {
    id: 'N-16',
    criterion: 'Refund reverses ticket status, inventory, ledger, commission, and notifications correctly.',
    section: 'H/I',
    evidence: ['tests/integration/supportTimeline.test.js', 'tests/integration/financeSettlement.test.js', 'tests/integration/financeWalletSettlementI.test.js'],
    backend: ['refund requests', 'timeline', 'ledger debit', 'commission reversal'],
    frontend: ['support/refund dashboards'],
  },
  {
    id: 'N-17',
    criterion: 'Promoter referral link attributes booking and releases commission after check-in/completion.',
    section: 'J/I',
    evidence: ['tests/integration/bookingFlow.test.js', 'tests/integration/promoterAgentSystemJ.test.js', 'tests/integration/financeSettlement.test.js'],
    backend: ['referral click/session', 'campaign conversion', 'commission release'],
    frontend: ['promoter dashboard and reports'],
  },
  {
    id: 'N-18',
    criterion: 'Support correspondence appears on booking timeline and sends notification attempts.',
    section: 'H',
    evidence: ['tests/integration/correspondenceSupportH.test.js', 'tests/integration/supportTimeline.test.js'],
    backend: ['correspondence messages', 'timeline events', 'delivery attempts'],
    frontend: ['customer/company/admin support pages'],
  },
  {
    id: 'N-19',
    criterion: 'Suspended or unverified company cannot publish or receive bookings.',
    section: 'A/C/E/M',
    evidence: ['tests/integration/onboardingAComplete.test.js', 'tests/integration/busOperationsC.test.js', 'tests/integration/multiServiceCartE.test.js', 'tests/integration/securityReliabilityM.test.js'],
    backend: ['verification gate', 'publish gate', 'checkout validation'],
    frontend: ['company publish action and checkout recovery'],
  },
  {
    id: 'N-20',
    criterion: 'Unified dashboard sidebar renders consistently across all roles.',
    section: 'L',
    evidence: ['tests/integration/unifiedDashboardLayoutL.test.js'],
    backend: ['dashboard shell config'],
    frontend: ['shared sidebar/topbar partials'],
  },
  {
    id: 'N-21',
    criterion: 'Future services are either fully bookable or safely hidden/coming soon without broken flows.',
    section: 'K/E',
    evidence: ['tests/integration/futureServicesK.test.js', 'tests/integration/multiServiceCartE.test.js'],
    backend: ['future service registry', 'checkout guard'],
    frontend: ['coming-soon architecture pages'],
  },
];

module.exports = acceptanceMatrix;
