module.exports = [
  { key: 'bus', label: 'Bus', icon: 'fa-bus', bookable: true, release: 'v1' },
  { key: 'hotel', label: 'Hotel', icon: 'fa-hotel', bookable: true, release: 'v1' },
  { key: 'flight', label: 'Flight', icon: 'fa-plane-departure', bookable: false, release: 'teaser' },
  { key: 'train', label: 'Train', icon: 'fa-train', bookable: false, release: 'architecture-ready' },
  { key: 'ferry', label: 'Ferry', icon: 'fa-ship', bookable: false, release: 'architecture-ready' },
  { key: 'tour', label: 'Tour', icon: 'fa-map-location-dot', bookable: false, release: 'architecture-ready' },
  { key: 'car_rental', label: 'Car rental', icon: 'fa-car', bookable: false, release: 'architecture-ready' },
  { key: 'airport_transfer', label: 'Airport transfer', icon: 'fa-van-shuttle', bookable: false, release: 'architecture-ready' },
  { key: 'event', label: 'Events', icon: 'fa-calendar-days', bookable: false, release: 'architecture-ready' },
  { key: 'cargo', label: 'Cargo', icon: 'fa-boxes-stacked', bookable: false, release: 'architecture-ready' },
  { key: 'visa', label: 'Visa support', icon: 'fa-passport', bookable: false, release: 'architecture-ready' },
  { key: 'insurance', label: 'Travel insurance', icon: 'fa-shield-heart', bookable: false, release: 'architecture-ready' },
  { key: 'package', label: 'Travel packages', icon: 'fa-suitcase-rolling', bookable: false, release: 'architecture-ready' },
];
