module.exports = [
  {
    id: 'route-guide-kampala-nairobi',
    slug: 'kampala-to-nairobi-route-guide',
    tag: 'Route guide',
    title: 'Kampala to Nairobi: what travelers should know',
    excerpt: 'Documents, boarding time, seat choice, baggage rules, and route confidence for cross-border coach travel.',
    body: 'Choose a departure that gives enough time for check-in, luggage loading, and border processing. Classic Trip keeps pickup points, document rules, seat locks, and ticket receipts in one place.',
    image: 'https://images.unsplash.com/photo-1517840901100-8179e982acb7?auto=format&fit=crop&w=1200&q=70',
    publishedAt: '2026-05-06T09:00:00.000Z',
  },
  {
    id: 'hotel-rooms-safely',
    slug: 'choose-rooms-houses-apartments-safely',
    tag: 'Stay tips',
    title: 'How to choose rooms, houses and apartments safely',
    excerpt: 'Compare amenities, room capacity, refund rules, check-in policy, and partner verification before booking.',
    body: 'Hotel partners can upload room, floor, and house layouts so guests understand the exact inventory they are booking. The backend keeps room reservations locked during checkout.',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=70',
    publishedAt: '2026-05-04T09:00:00.000Z',
  },
  {
    id: 'partner-promotions',
    slug: 'partner-promotions-get-bookings',
    tag: 'Promotion',
    title: 'How partner promotions help companies get bookings',
    excerpt: 'Sponsored placement, route boosts, promoter links, and campaign analytics for partner growth.',
    body: 'Sponsored listings can rank higher but they must always display a visible Sponsored badge. Promoters can share service links and earn commission when valid referrals convert.',
    image: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=70',
    publishedAt: '2026-05-01T09:00:00.000Z',
  },
  {
    id: 'ticket-access',
    slug: 'where-to-find-classic-trip-tickets',
    tag: 'Booking help',
    title: 'Where to find tickets after Gmail or WhatsApp delivery',
    excerpt: 'Ticket lookup, booking reference, phone/email matching, QR code, and receipts for guests.',
    body: 'After payment confirmation, the booking is stored in My Bookings, can be found by booking reference plus email or phone, and is ready for employee scanner validation.',
    image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1200&q=70',
    publishedAt: '2026-04-29T09:00:00.000Z',
  },
];
