const companies = [
  ['classic-express', 'Classic Express', 'bus', 'Uganda', 'Kampala', 'Verified regional coach operator with executive buses, AC, route support, and QR boarding.'],
  ['lakeline-vip', 'LakeLine VIP', 'bus', 'Uganda', 'Kampala', 'VIP coach service focused on Kampala, Nairobi, Kigali, and Dar corridors.'],
  ['northern-star', 'Northern Star', 'bus', 'Uganda', 'Gulu', 'Northern Uganda night coaches, parcel support, and employee scanner lanes.'],
  ['great-lakes-transit', 'Great Lakes Transit', 'bus', 'Rwanda', 'Kigali', 'Regional mobility partner for Rwanda, Uganda, Burundi, and eastern DRC corridors.'],
  ['coastline-transit', 'Coastline Transit', 'bus', 'Tanzania', 'Dar es Salaam', 'Long-distance coastal coach partner with border-ready schedule operations.'],
  ['speke-road-stays', 'Speke Road Stays', 'hotel', 'Uganda', 'Kampala', 'Business hotels and apartments for guests who need clean check-in and receipts.'],
  ['riverside-villas', 'Riverside Villas', 'hotel', 'Uganda', 'Jinja', 'River-view villas, family rooms, apartments, and group weekend stays.'],
  ['airport-suites', 'Airport Suites', 'hotel', 'Uganda', 'Entebbe', 'Airport hotel with shuttle-ready bookings and early check-in options.'],
  ['hill-view-rwanda', 'Hill View Rwanda', 'hotel', 'Rwanda', 'Kigali', 'Kigali city suites and partner apartments for business and tourism.'],
  ['sky-east-airways', 'SkyEast Airways', 'flight', 'Uganda', 'Entebbe', 'Flight teaser partner; booking remains read-only until provider integration.'],
  ['regional-air', 'Regional Air', 'flight', 'Kenya', 'Nairobi', 'Regional flight teaser partner for future provider inventory.'],
  ['ug-rail-partner', 'Uganda Rail Partner', 'train', 'Uganda', 'Kampala', 'Rail concept partner with route architecture ready for later release.'],
  ['lake-ferry-co', 'Lake Ferry Co.', 'ferry', 'Uganda', 'Entebbe', 'Ferry concept partner for passenger and cargo slot inventory.'],
  ['safarihub', 'SafariHub', 'tour', 'Uganda', 'Kampala', 'Tour operator with package routes, guides, rooms, and promotional campaigns.'],
  ['drive-east', 'DriveEast', 'car_rental', 'Uganda', 'Kampala', 'Vehicle rental partner with deposit, driver, and insurance workflows planned.'],
  ['event-east', 'EventEast', 'event', 'Uganda', 'Kampala', 'Event ticket partner profile for future event inventory and QR entry.'],
  ['cargo-link', 'Cargo Link East Africa', 'cargo', 'Kenya', 'Nairobi', 'Cargo movement concept partner for parcel and freight tickets.'],
  ['island-air', 'Island Air', 'flight', 'Tanzania', 'Zanzibar', 'Holiday flight teaser partner for future airline integrations.'],
  ['pearl-bus-lines', 'Pearl Bus Lines', 'bus', 'Uganda', 'Mbarara', 'Western Uganda coach operator with Kampala, Kabale, Fort Portal, and border routes.'],
  ['simba-coach', 'Simba Coach', 'bus', 'Kenya', 'Nairobi', 'Kenya regional coach partner with coast, lake, and cross-border routes.'],
  ['nile-grand-hotel', 'Nile Grand Hotel', 'hotel', 'Uganda', 'Jinja', 'Hotel and riverside stay partner with rooms, cottages, conference spaces, and family units.'],
  ['serengeti-stays', 'Serengeti Stays', 'hotel', 'Tanzania', 'Arusha', 'Safari-facing hotel partner for lodges, camps, apartments, and tour-linked stays.'],
  ['horn-air-connect', 'Horn Air Connect', 'flight', 'Ethiopia', 'Addis Ababa', 'Flight teaser partner for Ethiopia, Djibouti, Somalia, Eritrea, and regional routes.'],
  ['east-rail-link', 'East Rail Link', 'train', 'Kenya', 'Nairobi', 'Train architecture partner for intercity rail, coach inventory, and QR boarding.'],
  ['blue-lake-ferries', 'Blue Lake Ferries', 'ferry', 'Uganda', 'Entebbe', 'Lake transport partner for island trips, passenger ferries, and cargo slots.'],
  ['border-pass-assist', 'Border Pass Assist', 'visa', 'Uganda', 'Kampala', 'Travel document support partner for visas, border guidance, insurance, and trip readiness.'],
  ['safe-journey-cover', 'Safe Journey Cover', 'insurance', 'Uganda', 'Kampala', 'Travel insurance concept partner for trip protection, medical cover, and baggage claims.'],
  ['airport-connect', 'Airport Connect', 'airport_transfer', 'Uganda', 'Entebbe', 'Airport transfer partner with scheduled pickups, private cars, vans, and hotel shuttles.'],
  ['conference-east', 'Conference East', 'event', 'Rwanda', 'Kigali', 'Event and conference ticket partner for QR entry, group tickets, and partner promotions.'],
  ['regional-parcel', 'Regional Parcel', 'cargo', 'South Sudan', 'Juba', 'Parcel and cargo reservation partner for bus cargo, warehouse pickup, and cross-border freight.'],
];

module.exports = companies.map(([slug, name, companyType, country, city, description], index) => ({
  id: `company-${String(index + 1).padStart(2, '0')}`,
  ownerId: `user-company-${String(index + 1).padStart(2, '0')}`,
  name,
  slug,
  companyType,
  country,
  city,
  description,
  logo: { url: `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=4f8cff&color=fff&bold=true`, publicId: `classic-trip/companies/${slug}/logo` },
  coverImage: { url: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=70', publicId: `classic-trip/companies/${slug}/cover` },
  verificationStatus: index < 27 ? 'verified' : 'pending',
  documents: [{ secureUrl: '#', publicId: `classic-trip/companies/documents/${slug}-license`, resourceType: 'raw', label: 'Business license' }],
  supportContacts: { phone: '+256 700 000 00' + (index % 9), email: `support@${slug}.example`, whatsapp: '+256 700 000 999' },
  walletId: `wallet-company-${String(index + 1).padStart(2, '0')}`,
  ratingAverage: Number((4.1 + (index % 8) * 0.1).toFixed(1)),
  reviewCount: 45 + index * 13,
  settings: { instantConfirmation: companyType === 'bus' || companyType === 'hotel', canPublish: index < 27 },
  createdAt: new Date(Date.UTC(2026, 4, 1 + index)).toISOString(),
}));
