const { MongoRepository, mongoReady } = require('./mongoRepository');

const entityModelMap = {
  users: 'User',
  companies: 'Company',
  companyEmployees: 'CompanyEmployee',
  companyBranches: 'CompanyBranch',
  companyPolicies: 'CompanyPolicy',
  categories: 'ServiceCategory',
  serviceCategories: 'ServiceCategory',
  listings: 'Listing',
  routes: 'Route',
  routeStops: 'RouteStop',
  vehicles: 'Vehicle',
  schedules: 'TripSchedule',
  tripSchedules: 'TripSchedule',
  seats: 'Seat',
  driverAssignments: 'DriverAssignment',
  driverIncidents: 'DriverIncident',
  tripStatusUpdates: 'TripStatusUpdate',
  rooms: 'Room',
  hotelProperties: 'HotelProperty',
  roomTypes: 'RoomType',
  roomUnits: 'RoomUnit',
  roomNightInventories: 'RoomNightInventory',
  stayRules: 'StayRule',
  holds: 'InventoryHold',
  inventoryHolds: 'InventoryHold',
  carts: 'Cart',
  cartCheckoutAttempts: 'CartCheckoutAttempt',
  bookings: 'Booking',
  passengers: 'Passenger',
  payments: 'Payment',
  paymentWebhookEvents: 'PaymentWebhookEvent',
  correspondenceMessages: 'CorrespondenceMessage',
  bookingTimelineEvents: 'BookingTimelineEvent',
  notificationDeliveryAttempts: 'NotificationDeliveryAttempt',
  pushSubscriptions: 'PushSubscription',
  rescheduleRequests: 'RescheduleRequest',
  ticketScans: 'TicketScan',
  wallets: 'Wallet',
  walletTransactions: 'WalletTransaction',
  walletLedgerEntries: 'WalletTransaction',
  paymentIntents: 'PaymentIntent',
  receiptInvoices: 'ReceiptInvoice',
  taxFeeRecords: 'TaxFeeRecord',
  financeStatements: 'FinanceStatement',
  financeRiskReviews: 'FinanceRiskReview',
  settlementBatches: 'SettlementBatch',
  payoutRequests: 'PayoutRequest',
  payoutBatches: 'PayoutBatch',
  reconciliationReports: 'ReconciliationReport',
  commissions: 'Commission',
  promoterLinks: 'PromoterLink',
  referralClicks: 'ReferralClick',
  attributionSessions: 'AttributionSession',
  campaignConversions: 'CampaignConversion',
  agentProfiles: 'AgentProfile',
  offlineSales: 'OfflineSale',
  fraudSignals: 'FraudSignal',
  campaigns: 'PromotionCampaign',
  promotionCampaigns: 'PromotionCampaign',
  subscriptionOrders: 'SubscriptionOrder',
  subscriptions: 'Subscription',
  notifications: 'Notification',
  supportTickets: 'SupportTicket',
  refunds: 'RefundRequest',
  refundRequests: 'RefundRequest',
  partnerLeads: 'PartnerLead',
  discoverySessions: 'DiscoverySession',
  agreements: 'Agreement',
  invitations: 'Invitation',
  verificationReviews: 'VerificationReview',
  securityEvents: 'SecurityEvent',
  loginAudits: 'LoginAudit',
  deviceSessions: 'DeviceSession',
  idempotencyKeyRecords: 'IdempotencyKeyRecord',
  futureServiceModules: 'FutureServiceModule',
  flightOffers: 'FlightOffer',
  trainInventories: 'TrainInventory',
  tourPackageInventories: 'TourPackageInventory',
  carRentalUnits: 'CarRentalUnit',
  eventTicketInventories: 'EventTicketInventory',
  cargoShipments: 'CargoShipment',
  insurancePolicyRecords: 'InsurancePolicyRecord',
  corporateTravelAccounts: 'CorporateTravelAccount',
  loyaltyAccounts: 'LoyaltyAccount',
  reviews: 'Review',
  auditLogs: 'AuditLog',
  settings: 'Setting',
  platformSettings: 'PlatformSetting',
  savedListings: 'SavedListing',
  shiftHandovers: 'ShiftHandover',
  blogPosts: 'BlogPost',
  blogs: 'BlogPost',
};

const filterOverrides = {
  categories: (row) => ({ key: row.key || row.id }),
  serviceCategories: (row) => ({ key: row.key || row.id }),
  companies: (row) => ({ id: row.id }),
  companyBranches: (row) => ({ id: row.id }),
  companyPolicies: (row) => ({ id: row.id }),
  listings: (row) => ({ id: row.id }),
  routeStops: (row) => ({ id: row.id }),
  driverAssignments: (row) => ({ id: row.id }),
  driverIncidents: (row) => ({ id: row.id }),
  tripStatusUpdates: (row) => ({ id: row.id }),
  hotelProperties: (row) => ({ id: row.id }),
  roomTypes: (row) => ({ id: row.id }),
  roomUnits: (row) => ({ id: row.id }),
  roomNightInventories: (row) => ({ id: row.id }),
  stayRules: (row) => ({ id: row.id }),
  bookings: (row) => ({ bookingRef: row.bookingRef }),
  payments: (row) => ({ idempotencyKey: row.idempotencyKey || row.id }),
  paymentWebhookEvents: (row) => ({ provider: row.provider, idempotencyKey: row.idempotencyKey || row.id }),
  wallets: (row) => ({ ownerType: row.ownerType, ownerId: row.ownerId, currency: row.currency || 'UGX' }),
  promoterLinks: (row) => ({ id: row.id }),
  referralClicks: (row) => ({ id: row.id }),
  attributionSessions: (row) => ({ id: row.id }),
  campaignConversions: (row) => ({ bookingRef: row.bookingRef, promoterId: row.promoterId }),
  agentProfiles: (row) => ({ userId: row.userId || row.promoterId }),
  offlineSales: (row) => ({ saleRef: row.saleRef || row.id }),
  fraudSignals: (row) => ({ id: row.id }),
  subscriptionOrders: (row) => ({ orderRef: row.orderRef }),
  // PlatformSetting is a true singleton with no app-level id field - match the one
  // existing document (if any) so repeated upserts update it in place.
  platformSettings: () => ({}),
  savedListings: (row) => ({ userId: row.userId, listingId: row.listingId }),
  seats: (row) => ({ scheduleId: row.scheduleId, seatNumber: row.seatNumber }),
  rooms: (row) => ({ id: row.id }),
  holds: (row) => ({ id: row.id }),
  inventoryHolds: (row) => ({ id: row.id }),
  carts: (row) => ({ cartRef: row.cartRef || row.id }),
  cartCheckoutAttempts: (row) => ({ id: row.id }),
  correspondenceMessages: (row) => ({ id: row.id }),
  bookingTimelineEvents: (row) => ({ id: row.id }),
  notificationDeliveryAttempts: (row) => ({ id: row.id }),
  pushSubscriptions: (row) => ({ id: row.id }),
  rescheduleRequests: (row) => ({ id: row.id }),
  ticketScans: (row) => ({ id: row.id }),
  paymentIntents: (row) => ({ idempotencyKey: row.idempotencyKey || row.id }),
  receiptInvoices: (row) => ({ documentRef: row.documentRef || row.id }),
  taxFeeRecords: (row) => ({ id: row.id }),
  financeStatements: (row) => ({ statementRef: row.statementRef || row.id }),
  financeRiskReviews: (row) => ({ id: row.id }),
  settlementBatches: (row) => ({ batchNumber: row.batchNumber || row.id }),
  payoutRequests: (row) => ({ transactionId: row.transactionId || row.id }),
  payoutBatches: (row) => ({ batchNumber: row.batchNumber || row.id }),
  reconciliationReports: (row) => ({ id: row.id }),
  subscriptions: (row) => ({ id: row.id }),
  partnerLeads: (row) => ({ id: row.id }),
  discoverySessions: (row) => ({ id: row.id }),
  agreements: (row) => ({ id: row.id }),
  invitations: (row) => ({ tokenHash: row.tokenHash || row.id }),
  verificationReviews: (row) => ({ id: row.id }),
  securityEvents: (row) => ({ id: row.id }),
  loginAudits: (row) => ({ id: row.id }),
  deviceSessions: (row) => ({ sessionHash: row.sessionHash || row.id }),
  idempotencyKeyRecords: (row) => ({ key: row.key, scope: row.scope }),
  futureServiceModules: (row) => ({ key: row.key || row.id }),
  flightOffers: (row) => ({ id: row.id }),
  trainInventories: (row) => ({ id: row.id }),
  tourPackageInventories: (row) => ({ id: row.id }),
  carRentalUnits: (row) => ({ id: row.id }),
  eventTicketInventories: (row) => ({ id: row.id }),
  cargoShipments: (row) => ({ id: row.id }),
  insurancePolicyRecords: (row) => ({ id: row.id }),
  corporateTravelAccounts: (row) => ({ id: row.id }),
  loyaltyAccounts: (row) => ({ id: row.id }),
  settings: (row) => ({ key: row.key || row.id }),
};

const repositories = Object.fromEntries(Object.entries(entityModelMap).map(([entity, modelName]) => [
  entity,
  new MongoRepository({
    entity,
    modelName,
    defaultFilter: filterOverrides[entity] || ((row) => ({ id: row.id })),
  }),
]));

function repositoryFor(entity) {
  const repository = repositories[entity];
  if (!repository) {
    const error = new Error(`Unknown repository entity: ${entity}`);
    error.status = 404;
    throw error;
  }
  return repository;
}

module.exports = {
  ...repositories,
  entityModelMap,
  mongoReady,
  repositoryFor,
};
