const { Schema, model } = require('./_helpers');

const invitationSchema = new Schema({
  id: { type: String, index: true },
  token: { type: String, index: true },
  tokenHash: { type: String, index: true },
  tokenPreview: String,
  type: { type: String, enum: ['company', 'staff', 'driver', 'hotel', 'fleet_owner', 'promoter', 'agent', 'service_provider', 'admin'], default: 'company', index: true },
  status: { type: String, enum: ['draft', 'requested', 'sent', 'accepted', 'revoked', 'expired', 'rejected'], default: 'sent', index: true },
  email: { type: String, lowercase: true, trim: true, index: true },
  phone: String,
  fullName: String,
  companyId: { type: String, index: true },
  userId: { type: String, index: true },
  leadId: { type: String, index: true },
  agreementId: { type: String, index: true },
  companyName: String,
  role: { type: String, enum: ['super_admin', 'admin', 'finance_admin', 'support_admin', 'operations_admin', 'content_admin', 'company_admin', 'company_employee', 'driver', 'customer', 'promoter'] },
  roleTitle: String,
  permissions: [String],
  branchId: { type: String, index: true },
  vehicleId: { type: String, index: true },
  scheduleId: { type: String, index: true },
  licenseNumber: String,
  licenseClass: String,
  listingIds: [String],
  scheduleIds: [String],
  serviceCategories: [String],
  termsSummary: String,
  startDate: Date,
  requestedBy: String,
  sentBy: String,
  resentBy: String,
  revokedBy: String,
  acceptedBy: String,
  expiresAt: { type: Date, index: true },
  sentAt: Date,
  resentAt: Date,
  revokedAt: Date,
  acceptedAt: Date,
  rejectedAt: Date,
  rejectionReason: String,
  accountSetup: Schema.Types.Mixed,
  meta: Schema.Types.Mixed,
}, { timestamps: true });

invitationSchema.index({ type: 1, status: 1, createdAt: -1 });
invitationSchema.index({ companyId: 1, status: 1 });
module.exports = model('Invitation', invitationSchema);
