const { Schema, mediaSchema, model } = require('./_helpers');

const listingSchema = new Schema({
  id: { type: String, unique: true, sparse: true, index: true },
  companyId: { type: String, required: true, index: true },
  companySlug: String,
  companyName: String,
  branchId: { type: String, index: true },
  branchName: String,
  serviceType: { type: String, index: true, enum: ['bus', 'hotel', 'flight', 'local_transport', 'tour', 'car_rental', 'cargo'] },
  group: String,
  type: String,
  title: { type: String, required: true, text: true },
  slug: { type: String, required: true, index: true },
  sub: String,
  listingKind: { type: String, enum: ['operator_service', 'property', 'supplier_offer', 'transfer_service', 'experience', 'rental_vehicle', 'cargo_service'], index: true },
  shortDescription: String,
  operatorLicenceRef: String,
  salesChannels: [String],
  publication: Schema.Types.Mixed,
  country: String,
  city: { type: String, index: true },
  address: String,
  from: { type: String, index: true },
  to: { type: String, index: true },
  corridor: { type: String, index: true },
  priceFrom: Number,
  currency: { type: String, required: true, uppercase: true, trim: true },
  media: [mediaSchema],
  amenities: [String],
  checkInTime: String,
  checkOutTime: String,
  serviceNotes: String,
  contactPhone: String,
  pickupInstructions: String,
  dropoffInstructions: String,
  stayType: { type: String, index: true },
  pricingUnit: { type: String, default: 'per_booking' },
  inventory: { type: Number, min: 0, default: 0 },
  remainingInventory: { type: Number, min: 0, default: 0 },
  durationMinutes: { type: Number, min: 0 },
  maxGuests: { type: Number, min: 1 },
  minimumAge: { type: Number, min: 0 },
  vehicleCategory: String,
  transmission: String,
  fuelType: String,
  seatsCount: { type: Number, min: 1 },
  cargoTypes: [String],
  weightLimitKg: { type: Number, min: 0 },
  packageLimit: { type: Number, min: 1 },
  availabilityMode: { type: String, enum: ['on_demand', 'dated_capacity', 'date_range'], default: 'on_demand' },
  serviceDetails: Schema.Types.Mixed,
  ratingAverage: Number,
  reviewCount: Number,
  isSponsored: { type: Boolean, default: false, index: true },
  isFeatured: { type: Boolean, default: false, index: true },
  isVerified: { type: Boolean, default: false, index: true },
  bookable: { type: Boolean, default: false },
  releaseStatus: String,
  status: { type: String, enum: ['draft', 'active', 'paused', 'archived'], default: 'draft', index: true },
  policy: String,
  layout: String,
  taken: [String],
  cancellationRules: String,
  baggageRules: String,
}, { timestamps: true });

listingSchema.index({ title: 'text', city: 'text', from: 'text', to: 'text', companyName: 'text' });
module.exports = model('Listing', listingSchema);
